//! Crown & Ash — Core deterministic simulation engine.
//!
//! This crate implements the complete game logic for the Crown & Ash medieval
//! grand strategy game running on the Q-NarwhalKnight blockchain.
//!
//! # Public API
//!
//! - [`init_world`] — Create a new game world from a config and seed.
//! - [`tick`] — Advance the simulation by one turn (full 10-step pipeline).
//! - [`process_action`] — Submit a player action to the game world.
//! - [`query_world`] — Read-only query against the current world state.
//! - [`snapshot_world`] — Full world snapshot for client consumption.
//! - [`queue_action`] — Queue an action for processing on the next tick.
//!
//! # Determinism
//!
//! Every computation in this crate is deterministic. All RNG is derived from
//! block hashes via [`DeterministicRng`]. **No floating point** is used anywhere;
//! all numeric game state uses [`FixedPoint`](crown_ash_types::FixedPoint) (i64 x 1000).
//!
//! # Design Rules
//! - **No floating point** — all arithmetic uses `FixedPoint` (i64 * 1000).
//! - **No randomness from OS** — RNG is seeded exclusively from the block hash.
//! - **No allocation-heavy paths** — the entire tick must complete within the WASM
//!   gas budget (~10M gas).
//!
//! # Modules
//!
//! | Module       | Purpose                                        |
//! |--------------|------------------------------------------------|
//! | `world_state`| `GameWorld` struct holding all mutable state    |
//! | `world_gen`  | Initial world generation from seed              |
//! | `tick`       | 10-step turn pipeline                           |
//! | `combat`     | Auto-resolved battle math                       |
//! | `economy`    | Tax collection and prosperity                   |
//! | `cohesion`   | Realm stability decay and modifiers             |
//! | `succession` | Ruler death and heir resolution                 |
//! | `events`     | Random events (plague, famine, harvest, etc.)   |
//! | `ai`         | Heuristic NPC decision-making                   |
//! | `map`        | Fixed 25-province adjacency graph               |
//! | `random`     | Deterministic RNG from block hashes             |
//! | `trade`      | Inter-province trade routes and income           |
//! | `religion`   | Religious authority, gradual conversion, events  |
//! | `diplomacy`  | Vassal tribute, treaty expiry, coalitions        |
//! | `education`  | Age-gated skill growth, mentors, graduation      |

pub mod world_state;
pub mod world_gen;
pub mod random;
pub mod map;
pub mod tick;
pub mod combat;
pub mod economy;
pub mod cohesion;
pub mod succession;
pub mod realm_split;
pub mod events;
pub mod ai;
pub mod birth;
pub mod intrigue;
pub mod lifecycle;
pub mod trade;
pub mod religion;
pub mod diplomacy;
pub mod education;
pub mod relationships;

// Re-export key types at crate root.
pub use world_state::GameWorld;
pub use world_gen::init_world;
pub use random::DeterministicRng;

use crown_ash_types::*;
use crown_ash_types::diplomacy::{ActiveTreaty, Grievance};
use crown_ash_types::province::Troops;
use serde::{Deserialize, Serialize};

// ---------------------------------------------------------------------------
// Public API: tick (10-step turn pipeline)
// ---------------------------------------------------------------------------

/// Advance the world by one game turn.  Returns a `TurnSummary` of everything
/// that happened.  `block_hash` provides the per-turn entropy.
///
/// The 10-step pipeline:
/// 1. Age characters (natural death checks)
/// 2. Process queued player actions + NPC AI
/// 3. Resolve battles
/// 4. Move armies
/// 5. Economy (taxes, improvements, population)
/// 6. Unrest calculation
/// 7. Cohesion decay
/// 8. Random events (plague, famine, harvest, rebellion)
/// 9. Succession check
/// 10. Build TurnSummary
pub fn tick(world: &mut GameWorld, block_hash: &[u8; 32]) -> TurnSummary {
    tick::tick(world, *block_hash)
}

// ---------------------------------------------------------------------------
// Public API: process_action (QueuedAction-based interface)
// ---------------------------------------------------------------------------

/// Process a single player action against the current world state.
/// Returns a list of events generated by the action (may be empty).
pub fn process_action(world: &mut GameWorld, action: &QueuedAction) -> Vec<GameEvent> {
    let mut events = Vec::new();
    let turn = world.meta.turn;

    // Find the faction this wallet controls.
    let faction_id = match world.realm_by_wallet(&action.wallet) {
        Some(r) => r.faction,
        None => return events, // wallet not registered
    };

    match &action.action {
        GameAction::RaiseArmy { province } => {
            if let Some(prov) = world.province_mut_dirty(*province) {
                if prov.controller == faction_id && prov.garrison.levy >= 100 {
                    let levy_count = prov.garrison.levy / 2;
                    prov.garrison.levy -= levy_count;
                    let army_id = world.alloc_army_id();
                    let army = Army {
                        id: army_id,
                        owner_faction: faction_id,
                        commander: None,
                        troops: Troops {
                            levy: levy_count,
                            men_at_arms: 0,
                            knights: 0,
                        },
                        morale: FixedPoint::from_int(800),
                        location: *province,
                        destination: None,
                        movement_queue: Vec::new(),
                        raised_turn: turn,
                        supply: FixedPoint::from_int(100),
                        siege: None,
                    };
                    world.dirty.dirty_armies.insert(army_id);
                    world.dirty.armies_added.push(army_id);
                    world.armies.push(army);
                }
            }
        }
        GameAction::MoveArmy { army, target } => {
            let adjacent = world
                .army(*army)
                .and_then(|a| world.province(a.location))
                .map(|p| p.neighbors.contains(target))
                .unwrap_or(false);
            let owns = world.army(*army).map(|a| a.owner_faction == faction_id).unwrap_or(false);
            if adjacent && owns {
                if let Some(a) = world.army_mut_dirty(*army) {
                    a.destination = Some(*target);
                    a.movement_queue.clear(); // cancel any multi-hop
                }
            }
        }
        GameAction::MoveArmyPath { army, target } => {
            let owns = world.army(*army).map(|a| a.owner_faction == faction_id).unwrap_or(false);
            let location = world.army(*army).map(|a| a.location);
            if owns {
                if let Some(loc) = location {
                    if let Some(path) = map::find_path(loc, *target) {
                        if !path.is_empty() {
                            if let Some(a) = world.army_mut_dirty(*army) {
                                a.movement_queue = path;
                                a.destination = None;
                            }
                        }
                    }
                }
            }
        }
        GameAction::DisbandArmy { army } => {
            if let Some(pos) = world
                .armies
                .iter()
                .position(|a| a.id == *army && a.owner_faction == faction_id)
            {
                let disbanded = world.armies.remove(pos);
                world.dirty.armies_removed.push(disbanded.id);
                if let Some(prov) = world.province_mut_dirty(disbanded.location) {
                    prov.garrison.levy += disbanded.troops.levy;
                    prov.garrison.men_at_arms += disbanded.troops.men_at_arms;
                    prov.garrison.knights += disbanded.troops.knights;
                }
            }
        }
        GameAction::DeclareWar {
            target,
            casus_belli,
        } => {
            let target_id = *target;
            if target_id != faction_id {
                let realm_count = world.realms.len();
                for ridx in 0..realm_count {
                    if world.realms[ridx].faction == faction_id && !world.realms[ridx].at_war_with.contains(&target_id) {
                        world.realms[ridx].at_war_with.push(target_id);
                        world.dirty.dirty_realms.insert(faction_id);
                    }
                    if world.realms[ridx].faction == target_id && !world.realms[ridx].at_war_with.contains(&faction_id) {
                        world.realms[ridx].at_war_with.push(faction_id);
                        world.dirty.dirty_realms.insert(target_id);
                    }
                }
                if let Some(rel) = world.relation_mut_dirty(faction_id, target_id) {
                    rel.at_war = true;
                    rel.opinion -= FixedPoint::from_int(100);
                    rel.grievances.push(Grievance {
                        reason: format!("Declared war ({:?})", casus_belli),
                        opinion_modifier: FixedPoint::from_int(-100),
                        inflicted_turn: turn,
                        decay_turns_remaining: 200,
                    });
                }
                events.push(GameEvent::WarDeclared {
                    attacker: faction_id,
                    defender: target_id,
                    casus_belli: format!("{:?}", casus_belli),
                    turn,
                });
            }
        }
        GameAction::ProposeTreaty { target, treaty } => {
            let target_id = *target;
            let _ = apply_treaty(world, faction_id, target_id, *treaty);
            events.push(GameEvent::TreatySigned {
                faction_a: faction_id,
                faction_b: target_id,
                treaty_type: format!("{:?}", treaty),
                turn,
            });
        }
        GameAction::AcceptTreaty { from, treaty } => {
            let _ = apply_treaty(world, *from, faction_id, *treaty);
            events.push(GameEvent::TreatySigned {
                faction_a: *from,
                faction_b: faction_id,
                treaty_type: format!("{:?}", treaty),
                turn,
            });
        }
        GameAction::BuildImprovement {
            province,
            improvement,
        } => {
            let cost = improvement.build_cost_gold();
            let can_afford = world
                .realm_for_faction(faction_id)
                .map(|r| r.treasury >= cost)
                .unwrap_or(false);
            let owns = world
                .province(*province)
                .map(|p| p.controller == faction_id)
                .unwrap_or(false);
            let already_built = world
                .province(*province)
                .map(|p| p.improvements.contains(improvement))
                .unwrap_or(false);
            let in_queue = world
                .province(*province)
                .map(|p| p.construction_queue.iter().any(|&(imp, _)| imp == *improvement))
                .unwrap_or(false);
            if owns && can_afford && !already_built && !in_queue {
                if let Some(realm) = world.realm_for_faction_mut_dirty(faction_id) {
                    realm.treasury = realm.treasury - cost;
                }
                if let Some(prov) = world.province_mut_dirty(*province) {
                    prov.construction_queue
                        .push((*improvement, improvement.build_turns()));
                }
            }
        }
        GameAction::SetTaxRate { province, rate } => {
            if let Some(prov) = world.province_mut_dirty(*province) {
                if prov.controller == faction_id {
                    prov.tax_rate = (*rate).clamp(FixedPoint::ZERO, FixedPoint::ONE);
                }
            }
        }
        GameAction::AssignCouncilor { character, role } => {
            let char_faction = world.character(*character).map(|c| c.faction);
            if char_faction == Some(faction_id) {
                let target_role = match role {
                    CouncilRole::Marshal => CharacterRole::Marshal,
                    CouncilRole::Chaplain => CharacterRole::Chaplain,
                    CouncilRole::Steward => CharacterRole::Steward,
                    CouncilRole::Spymaster => CharacterRole::Spymaster,
                };
                let char_count = world.characters.len();
                for cidx in 0..char_count {
                    if world.characters[cidx].faction == faction_id
                        && world.characters[cidx].role == target_role
                        && world.characters[cidx].id != *character
                    {
                        world.characters[cidx].role = CharacterRole::Courtier;
                        world.dirty.dirty_characters.insert(world.characters[cidx].id);
                    }
                }
                if let Some(c) = world.character_mut_dirty(*character) {
                    c.role = target_role;
                }
            }
        }
        GameAction::DesignateHeir { character } => {
            let char_faction = world.character(*character).map(|c| c.faction);
            if char_faction == Some(faction_id) {
                let ruler_id = world.realm_for_faction(faction_id).map(|r| r.ruler);
                if let Some(rid) = ruler_id {
                    if let Some(ruler) = world.character_mut_dirty(rid) {
                        ruler.heir = Some(*character);
                    }
                    if let Some(heir) = world.character_mut_dirty(*character) {
                        heir.role = CharacterRole::Heir;
                    }
                }
            }
        }
        GameAction::ArrangeMarriage { a, b } => {
            let a_ok = world.character(*a).map(|c| c.alive && c.is_adult() && c.spouse.is_none()).unwrap_or(false);
            let b_ok = world.character(*b).map(|c| c.alive && c.is_adult() && c.spouse.is_none()).unwrap_or(false);
            let a_faction = world.character(*a).map(|c| c.faction);
            let b_faction = world.character(*b).map(|c| c.faction);
            let one_ours = a_faction == Some(faction_id) || b_faction == Some(faction_id);
            if a_ok && b_ok && one_ours {
                if let Some(ca) = world.character_mut_dirty(*a) {
                    ca.spouse = Some(*b);
                }
                if let Some(cb) = world.character_mut_dirty(*b) {
                    cb.spouse = Some(*a);
                }
                // Diplomatic opinion boost for cross-faction marriage.
                if a_faction != b_faction {
                    if let (Some(fa), Some(fb)) = (a_faction, b_faction) {
                        if let Some(rel) = world.relation_mut_dirty(fa, fb) {
                            rel.opinion += FixedPoint::from_int(30);
                        }
                    }
                }
                // Set up personal relationship + alliance event.
                let mut _marriage_events = Vec::new();
                relationships::on_marriage(world, *a, *b, &mut _marriage_events, world.meta.turn);
            }
        }
        GameAction::ConvertProvince { province, religion } => {
            let owns = world.province(*province)
                .map(|p| p.controller == faction_id)
                .unwrap_or(false);
            let different = world.province(*province)
                .map(|p| p.religion != *religion)
                .unwrap_or(false);
            let not_already_converting = world.province(*province)
                .map(|p| p.conversion_progress.is_none())
                .unwrap_or(false);
            if owns && different && not_already_converting {
                // Start gradual conversion (progress 0 → 1000 over multiple turns).
                if let Some(prov) = world.province_mut_dirty(*province) {
                    prov.conversion_progress = Some((*religion, FixedPoint::ZERO));
                    // Small initial unrest from announcing conversion.
                    prov.unrest += FixedPoint::from_int(30);
                }
            }
        }
        GameAction::LaunchPlot { target, plot_type } => {
            // Find a character in the player's faction to be the instigator (the ruler).
            let ruler_id = world.realm_for_faction(faction_id).map(|r| r.ruler);
            if let Some(instigator_id) = ruler_id {
                if let Ok(plot_id) = intrigue::launch_plot(world, instigator_id, *target, *plot_type) {
                    events.push(GameEvent::PlotLaunched {
                        instigator: instigator_id,
                        target: *target,
                        plot_type: plot_type.label().to_string(),
                        turn,
                    });
                    let _ = plot_id;
                }
            }
        }
        GameAction::BackPlot { plot_id } => {
            // Find a courtier or councillor to back the plot.
            let backer = world
                .characters
                .iter()
                .find(|c| {
                    c.faction == faction_id
                        && c.alive
                        && c.role != CharacterRole::Ruler
                        && c.role != CharacterRole::Heir
                })
                .map(|c| c.id);
            if let Some(backer_id) = backer {
                let _ = intrigue::back_plot(world, *plot_id, backer_id);
            }
        }
        GameAction::InvestigatePlot { spymaster } => {
            // Verify the spymaster belongs to the player's faction.
            let valid = world
                .character(*spymaster)
                .map(|c| c.faction == faction_id && c.role == CharacterRole::Spymaster && c.alive)
                .unwrap_or(false);
            if valid {
                let mut rng = random::DeterministicRng::new([turn as u8; 32], "investigate");
                let investigate_events = intrigue::investigate_plot(world, *spymaster, &mut rng);
                events.extend(investigate_events);
            }
        }
        GameAction::EstablishTradeRoute { from, to } => {
            // Validate: player controls 'from' province.
            let owns_from = world.province(*from)
                .map(|p| p.controller == faction_id)
                .unwrap_or(false);
            // Validate: provinces are adjacent.
            let adjacent = world.province(*from)
                .map(|p| p.neighbors.contains(to))
                .unwrap_or(false);
            // Validate: no existing route between these two.
            let already_exists = world.trade_routes.iter().any(|r| {
                (r.province_a == *from && r.province_b == *to)
                    || (r.province_a == *to && r.province_b == *from)
            });
            // Validate: per-province cap not exceeded for either endpoint.
            let routes_from = trade::routes_for_province(world, *from);
            let routes_to = trade::routes_for_province(world, *to);
            // Validate: global cap not exceeded.
            let under_global_cap = world.trade_routes.len() < trade::MAX_TRADE_ROUTES;

            if owns_from
                && adjacent
                && !already_exists
                && routes_from < trade::MAX_ROUTES_PER_PROVINCE
                && routes_to < trade::MAX_ROUTES_PER_PROVINCE
                && under_global_cap
            {
                let route_id = world.alloc_trade_route_id();
                let goods = trade_good_for_province(world, *from);
                world.trade_routes.push(TradeRoute {
                    id: route_id,
                    province_a: *from,
                    province_b: *to,
                    goods,
                    volume: FixedPoint::from_int(trade::INITIAL_VOLUME),
                    established_turn: turn,
                    disrupted: false,
                });
                events.push(GameEvent::TradeRouteEstablished {
                    from: *from,
                    to: *to,
                    goods: goods.label().to_string(),
                    turn,
                });
            }
        }
        GameAction::DisruptTradeRoute { route_id } => {
            // Extract route endpoint data first (immutable borrow).
            let route_data = world.trade_routes.iter()
                .find(|r| r.id == *route_id)
                .map(|r| (r.province_a, r.province_b));

            if let Some((prov_a, prov_b)) = route_data {
                // Check that the disrupting player is at war with at least
                // one endpoint's controller.
                let ctrl_a = world.province(prov_a).map(|p| p.controller);
                let ctrl_b = world.province(prov_b).map(|p| p.controller);
                let at_war_with_a = ctrl_a.map_or(false, |c| world.at_war(faction_id, c));
                let at_war_with_b = ctrl_b.map_or(false, |c| world.at_war(faction_id, c));

                if at_war_with_a || at_war_with_b {
                    // Now take the mutable borrow to update the route.
                    if let Some(route) = world.trade_routes.iter_mut().find(|r| r.id == *route_id) {
                        route.disrupted = true;
                    }
                    events.push(GameEvent::TradeRouteDisrupted {
                        from: prov_a,
                        to: prov_b,
                        reason: "Raided by enemy faction".to_string(),
                        turn,
                    });
                }
            }
        }
    }

    events
}

/// Determine the primary trade good exported by a province based on its improvements.
fn trade_good_for_province(world: &GameWorld, province_id: u16) -> TradeGood {
    let improvements = match world.province(province_id) {
        Some(p) => &p.improvements,
        None => return TradeGood::Luxuries,
    };

    if improvements.contains(&Improvement::Farmstead) {
        TradeGood::Grain
    } else if improvements.contains(&Improvement::Mine) {
        TradeGood::Iron
    } else if improvements.contains(&Improvement::Lumbercamp) {
        TradeGood::Timber
    } else if improvements.contains(&Improvement::Quarry) {
        TradeGood::Stone
    } else if improvements.contains(&Improvement::Stables) {
        TradeGood::Horses
    } else if improvements.contains(&Improvement::Temple) {
        TradeGood::Faith
    } else {
        TradeGood::Luxuries
    }
}

// ---------------------------------------------------------------------------
// Internal action processing (used by tick pipeline for NPC + queued actions)
// ---------------------------------------------------------------------------

/// Validate and apply a game action from the tick pipeline.
///
/// This is used internally by `tick::tick` for processing queued player actions
/// and AI-generated NPC actions.
pub(crate) fn process_action_internal(
    world: &mut GameWorld,
    wallet: &str,
    action: GameAction,
) -> Result<(), String> {
    if wallet.is_empty() {
        return process_npc_action(world, action);
    }

    let qa = QueuedAction {
        wallet: wallet.to_string(),
        action,
        submitted_turn: world.meta.turn,
    };
    let _ = process_action(world, &qa);
    Ok(())
}

/// Process an NPC action (no wallet).
fn process_npc_action(world: &mut GameWorld, action: GameAction) -> Result<(), String> {
    let turn = world.meta.turn;
    match action {
        GameAction::RaiseArmy { province } => {
            let prov = world.province(province).ok_or("Province not found")?;
            let controller = prov.controller;
            let population = prov.population;

            let levy = (population / 20).max(50);
            let maa = (population / 100).max(10);
            let knights = (population / 1000).max(1) as u16;

            let army_id = world.alloc_army_id();
            world.dirty.dirty_armies.insert(army_id);
            world.dirty.armies_added.push(army_id);
            world.armies.push(Army {
                id: army_id,
                owner_faction: controller,
                commander: None,
                troops: Troops { levy, men_at_arms: maa, knights },
                morale: FixedPoint::from_int(600),
                location: province,
                destination: None,
                movement_queue: Vec::new(),
                raised_turn: turn,
                supply: FixedPoint::from_int(100),
                siege: None,
            });
            Ok(())
        }
        GameAction::MoveArmy { army, target } => {
            let adjacent = world.army(army)
                .and_then(|a| world.province(a.location))
                .map(|p| p.neighbors.contains(&target))
                .unwrap_or(false);
            if !adjacent {
                return Err("Target not adjacent".to_string());
            }
            if let Some(a) = world.army_mut_dirty(army) {
                a.destination = Some(target);
                a.movement_queue.clear();
            }
            Ok(())
        }
        GameAction::MoveArmyPath { army, target } => {
            let location = world.army(army).map(|a| a.location);
            if let Some(loc) = location {
                if let Some(path) = map::find_path(loc, target) {
                    if !path.is_empty() {
                        if let Some(a) = world.army_mut_dirty(army) {
                            a.movement_queue = path;
                            a.destination = None;
                        }
                    }
                }
            }
            Ok(())
        }
        GameAction::DeclareWar { target, casus_belli } => {
            let target_id = target;
            // Find which NPC faction borders the target.
            let attacker = {
                let mut found = None;
                for realm in &world.realms {
                    if realm.owner_wallet.is_empty() && !realm.at_war_with.contains(&target_id) {
                        let borders = world.provinces.iter().any(|p| {
                            p.controller == realm.faction
                                && p.neighbors.iter().any(|&n| {
                                    world.province(n).map_or(false, |np| np.controller == target_id)
                                })
                        });
                        if borders {
                            found = Some(realm.faction);
                            break;
                        }
                    }
                }
                found.ok_or("No NPC faction found to declare war")?
            };

            let realm_count = world.realms.len();
            for ridx in 0..realm_count {
                if world.realms[ridx].faction == attacker && !world.realms[ridx].at_war_with.contains(&target_id) {
                    world.realms[ridx].at_war_with.push(target_id);
                    world.dirty.dirty_realms.insert(attacker);
                }
                if world.realms[ridx].faction == target_id && !world.realms[ridx].at_war_with.contains(&attacker) {
                    world.realms[ridx].at_war_with.push(attacker);
                    world.dirty.dirty_realms.insert(target_id);
                }
            }
            if let Some(rel) = world.relation_mut_dirty(attacker, target_id) {
                rel.at_war = true;
                rel.opinion -= FixedPoint::from_int(100);
                rel.grievances.push(Grievance {
                    reason: format!("Declared war ({:?})", casus_belli),
                    opinion_modifier: FixedPoint::from_int(-100),
                    inflicted_turn: turn,
                    decay_turns_remaining: 200,
                });
            }
            Ok(())
        }
        GameAction::ProposeTreaty { target, treaty } => {
            if treaty == TreatyType::WhitePeace {
                let proposer = world.realms.iter()
                    .find(|r| r.owner_wallet.is_empty() && r.at_war_with.contains(&target))
                    .map(|r| r.faction);
                if let Some(p) = proposer {
                    return apply_treaty(world, p, target, treaty);
                }
            }
            Err("NPC treaty proposal not handled".to_string())
        }
        GameAction::BuildImprovement { province, improvement } => {
            let prov = world.province(province).ok_or("Province not found")?;
            let controller = prov.controller;
            let cost = improvement.build_cost_gold();
            let can_afford = world.realm_for_faction(controller)
                .map(|r| r.treasury >= cost)
                .unwrap_or(false);
            let already_built = prov.improvements.contains(&improvement);
            let in_queue = prov.construction_queue.iter().any(|&(imp, _)| imp == improvement);

            if can_afford && !already_built && !in_queue {
                if let Some(realm) = world.realm_for_faction_mut_dirty(controller) {
                    realm.treasury = realm.treasury - cost;
                }
                if let Some(p) = world.province_mut_dirty(province) {
                    p.construction_queue.push((improvement, improvement.build_turns()));
                }
            }
            Ok(())
        }
        _ => Ok(()),
    }
}

// ---------------------------------------------------------------------------
// Treaty application
// ---------------------------------------------------------------------------

fn apply_treaty(world: &mut GameWorld, faction_a: u8, faction_b: u8, treaty: TreatyType) -> Result<(), String> {
    let turn = world.meta.turn;
    match treaty {
        TreatyType::WhitePeace | TreatyType::Surrender => {
            if let Some(rel) = world.relation_mut_dirty(faction_a, faction_b) {
                rel.at_war = false;
                rel.treaties.push(ActiveTreaty {
                    treaty_type: format!("{:?}", treaty),
                    signed_turn: turn,
                    expires_turn: None,
                });
            }
            if let Some(realm) = world.realm_for_faction_mut_dirty(faction_a) {
                realm.at_war_with.retain(|&f| f != faction_b);
            }
            if let Some(realm) = world.realm_for_faction_mut_dirty(faction_b) {
                realm.at_war_with.retain(|&f| f != faction_a);
            }
        }
        TreatyType::NonAggression => {
            if let Some(rel) = world.relation_mut_dirty(faction_a, faction_b) {
                rel.treaties.push(ActiveTreaty {
                    treaty_type: "NonAggression".into(),
                    signed_turn: turn,
                    expires_turn: Some(turn + 100),
                });
                rel.opinion += FixedPoint::from_int(30);
            }
        }
        TreatyType::DefensiveAlliance => {
            if let Some(rel) = world.relation_mut_dirty(faction_a, faction_b) {
                rel.treaties.push(ActiveTreaty {
                    treaty_type: "DefensiveAlliance".into(),
                    signed_turn: turn,
                    expires_turn: None,
                });
                rel.opinion += FixedPoint::from_int(50);
            }
            if let Some(realm) = world.realm_for_faction_mut_dirty(faction_a) {
                if !realm.allies.contains(&faction_b) {
                    realm.allies.push(faction_b);
                }
            }
            if let Some(realm) = world.realm_for_faction_mut_dirty(faction_b) {
                if !realm.allies.contains(&faction_a) {
                    realm.allies.push(faction_a);
                }
            }
        }
        TreatyType::TradeAgreement => {
            if let Some(rel) = world.relation_mut_dirty(faction_a, faction_b) {
                rel.treaties.push(ActiveTreaty {
                    treaty_type: "TradeAgreement".into(),
                    signed_turn: turn,
                    expires_turn: Some(turn + 50),
                });
                rel.opinion += FixedPoint::from_int(20);
            }
        }
        TreatyType::Marriage => {
            if let Some(rel) = world.relation_mut_dirty(faction_a, faction_b) {
                rel.treaties.push(ActiveTreaty {
                    treaty_type: "Marriage".into(),
                    signed_turn: turn,
                    expires_turn: None,
                });
                rel.opinion += FixedPoint::from_int(40);
            }
        }
        TreatyType::Vassalization => {
            if let Some(rel) = world.relation_mut_dirty(faction_a, faction_b) {
                rel.treaties.push(ActiveTreaty {
                    treaty_type: "Vassalization".into(),
                    signed_turn: turn,
                    expires_turn: None,
                });
            }
            if let Some(realm) = world.realm_for_faction_mut_dirty(faction_a) {
                if !realm.vassals.contains(&faction_b) {
                    realm.vassals.push(faction_b);
                }
            }
        }
    }
    Ok(())
}

// ---------------------------------------------------------------------------
// Queue action (for submission via blockchain transaction)
// ---------------------------------------------------------------------------

/// Queue a player action for processing on the next tick.
///
/// Actions are stored in `world.action_queue` and processed in Step 2 of the
/// tick pipeline.
pub fn queue_action(world: &mut GameWorld, wallet: &str, action: GameAction) {
    world.action_queue.push(QueuedAction {
        wallet: wallet.to_string(),
        action,
        submitted_turn: world.meta.turn,
    });
}

// ---------------------------------------------------------------------------
// Queries
// ---------------------------------------------------------------------------

/// Supported read-only queries against the game world.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum WorldQuery {
    /// Full metadata snapshot (turn, player count, etc.).
    Meta,
    /// Single province by ID.
    Province(ProvinceId),
    /// All provinces.
    AllProvinces,
    /// Single faction by ID.
    Faction(u8),
    /// All factions.
    AllFactions,
    /// Single character by ID.
    Character(u32),
    /// Characters belonging to a faction.
    FactionCharacters(u8),
    /// All armies.
    AllArmies,
    /// Armies belonging to a faction.
    FactionArmies(u8),
    /// Diplomatic relation between two factions.
    Diplomacy(u8, u8),
    /// A realm by faction ID.
    Realm(u8),
}

/// Serialisable snapshot of the game world for client consumption.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WorldSnapshot {
    pub turn: u32,
    pub player_count: u8,
    pub provinces: Vec<Province>,
    pub characters: Vec<Character>,
    pub factions: Vec<Faction>,
    pub realms: Vec<Realm>,
    pub armies: Vec<Army>,
    pub diplomacy: Vec<DiplomaticRelation>,
}

/// Execute a read-only query and return JSON bytes.
pub fn query_world(world: &GameWorld, query: &WorldQuery) -> Vec<u8> {
    match query {
        WorldQuery::Meta => serde_json::to_vec(&world.meta).unwrap_or_default(),
        WorldQuery::Province(id) => {
            let p = world.province(*id);
            serde_json::to_vec(&p).unwrap_or_default()
        }
        WorldQuery::AllProvinces => serde_json::to_vec(&world.provinces).unwrap_or_default(),
        WorldQuery::Faction(id) => {
            let f = world.faction(*id);
            serde_json::to_vec(&f).unwrap_or_default()
        }
        WorldQuery::AllFactions => serde_json::to_vec(&world.factions).unwrap_or_default(),
        WorldQuery::Character(id) => {
            let c = world.character(*id);
            serde_json::to_vec(&c).unwrap_or_default()
        }
        WorldQuery::FactionCharacters(fid) => {
            let chars: Vec<_> = world
                .characters
                .iter()
                .filter(|c| c.faction == *fid)
                .collect();
            serde_json::to_vec(&chars).unwrap_or_default()
        }
        WorldQuery::AllArmies => serde_json::to_vec(&world.armies).unwrap_or_default(),
        WorldQuery::FactionArmies(fid) => {
            let armies: Vec<_> = world
                .armies
                .iter()
                .filter(|a| a.owner_faction == *fid)
                .collect();
            serde_json::to_vec(&armies).unwrap_or_default()
        }
        WorldQuery::Diplomacy(a, b) => {
            let rel = world.relation(*a, *b);
            serde_json::to_vec(&rel).unwrap_or_default()
        }
        WorldQuery::Realm(fid) => {
            let r = world.realm_for_faction(*fid);
            serde_json::to_vec(&r).unwrap_or_default()
        }
    }
}

/// Return a full snapshot of the world (all live characters, all entities).
pub fn snapshot_world(world: &GameWorld) -> WorldSnapshot {
    WorldSnapshot {
        turn: world.meta.turn,
        player_count: world.meta.player_count,
        provinces: world.provinces.clone(),
        characters: world.characters.iter().filter(|c| c.alive).cloned().collect(),
        factions: world.factions.clone(),
        realms: world.realms.clone(),
        armies: world.armies.clone(),
        diplomacy: world.diplomacy.clone(),
    }
}

/// Compute which provinces a faction can see (owns + adjacent to owned).
pub fn visible_provinces(world: &GameWorld, faction_id: u8) -> Vec<u16> {
    let mut visible = std::collections::HashSet::new();

    for p in &world.provinces {
        if p.controller == faction_id {
            visible.insert(p.id);
            // All neighbors are also visible.
            for &n in &p.neighbors {
                visible.insert(n);
            }
        }
    }

    let mut result: Vec<u16> = visible.into_iter().collect();
    result.sort_unstable();
    result
}

/// Return a fog-of-war snapshot filtered for a specific faction.
///
/// - Provinces outside visibility have population, garrison, resources, and
///   construction_queue hidden (zeroed out).
/// - Armies in non-visible provinces are excluded.
/// - Characters in non-visible factions with no visible armies are excluded.
/// - All factions and diplomacy are always visible (public knowledge).
pub fn snapshot_world_for_faction(world: &GameWorld, faction_id: u8) -> WorldSnapshot {
    let visible = visible_provinces(world, faction_id);

    // Filter provinces: show full data for visible, redacted for hidden.
    let provinces: Vec<Province> = world.provinces.iter().map(|p| {
        if visible.contains(&p.id) {
            p.clone()
        } else {
            // Redacted province: basic info only.
            Province {
                id: p.id,
                name: p.name.clone(),
                terrain: p.terrain,
                controller: p.controller,
                population: 0,           // hidden
                prosperity: FixedPoint::ZERO,
                unrest: FixedPoint::ZERO,
                fortification: 0,
                religion: p.religion,    // public knowledge
                culture: p.culture,      // public knowledge
                resources: crown_ash_types::province::Resources::default(),
                garrison: Troops::default(),
                improvements: vec![],
                construction_queue: vec![],
                scars: vec![],
                grudges: vec![],
                last_famine_turn: None,
                last_siege_turn: None,
                tax_rate: FixedPoint::ZERO,
                neighbors: p.neighbors.clone(),
                conversion_progress: None,
            }
        }
    }).collect();

    // Filter armies: only show those in visible provinces.
    let armies: Vec<Army> = world.armies.iter()
        .filter(|a| visible.contains(&a.location))
        .cloned()
        .collect();

    // Characters: show all in player's faction + characters with visible armies.
    let visible_army_commanders: std::collections::HashSet<u32> = armies.iter()
        .filter_map(|a| a.commander)
        .collect();

    let characters: Vec<Character> = world.characters.iter()
        .filter(|c| {
            c.alive && (
                c.faction == faction_id
                || visible_army_commanders.contains(&c.id)
                || c.role == CharacterRole::Ruler // rulers are public
            )
        })
        .cloned()
        .collect();

    WorldSnapshot {
        turn: world.meta.turn,
        player_count: world.meta.player_count,
        provinces,
        characters,
        factions: world.factions.clone(),
        realms: world.realms.clone(),
        armies,
        diplomacy: world.diplomacy.clone(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn tick_advances_turn() {
        let config = WorldConfig::default();
        let mut world = init_world(&config, [0xAA; 32]);
        assert_eq!(world.meta.turn, 0);

        let hash = [0xBB; 32];
        let summary = tick(&mut world, &hash);
        assert_eq!(summary.turn, 1);
        assert_eq!(world.meta.turn, 1);
    }

    #[test]
    fn tick_is_deterministic() {
        let config = WorldConfig::default();
        let hash = [0xCC; 32];

        let mut w1 = init_world(&config, [0xDD; 32]);
        let mut w2 = init_world(&config, [0xDD; 32]);

        let s1 = tick(&mut w1, &hash);
        let s2 = tick(&mut w2, &hash);

        assert_eq!(s1.turn, s2.turn);
        assert_eq!(s1.active_factions, s2.active_factions);
        assert_eq!(s1.total_population, s2.total_population);
        assert_eq!(s1.events.len(), s2.events.len());
    }

    #[test]
    fn query_meta_returns_json() {
        let config = WorldConfig::default();
        let world = init_world(&config, [0xEE; 32]);
        let bytes = query_world(&world, &WorldQuery::Meta);
        let meta: WorldMeta = serde_json::from_slice(&bytes).unwrap();
        assert!(meta.initialized);
    }

    #[test]
    fn process_action_declare_war() {
        let config = WorldConfig::default();
        let mut world = init_world(&config, [0xFF; 32]);
        world.realms[0].owner_wallet = "wallet_test".to_string();

        let action = QueuedAction {
            wallet: "wallet_test".to_string(),
            action: GameAction::DeclareWar {
                target: 1,
                casus_belli: CasusBelli::Conquest,
            },
            submitted_turn: 0,
        };

        let events = process_action(&mut world, &action);
        assert_eq!(events.len(), 1);
        assert!(world.realms[0].at_war_with.contains(&1));
        assert!(world.at_war(0, 1));
    }

    #[test]
    fn process_action_raise_army() {
        let config = WorldConfig::default();
        let mut world = init_world(&config, [0x42; 32]);
        world.realms[0].owner_wallet = "player1".to_string();

        let action = QueuedAction {
            wallet: "player1".to_string(),
            action: GameAction::RaiseArmy { province: 7 },
            submitted_turn: 0,
        };
        let _ = process_action(&mut world, &action);
        assert!(!world.armies.is_empty(), "Army should be raised");
    }

    #[test]
    fn process_action_build_improvement() {
        let config = WorldConfig::default();
        let mut world = init_world(&config, [0x42; 32]);
        world.realms[0].owner_wallet = "player1".to_string();
        let initial_gold = world.realms[0].treasury;

        let action = QueuedAction {
            wallet: "player1".to_string(),
            action: GameAction::BuildImprovement {
                province: 7,
                improvement: Improvement::Market,
            },
            submitted_turn: 0,
        };
        let _ = process_action(&mut world, &action);
        assert!(world.realms[0].treasury < initial_gold, "Gold should be deducted");
    }

    #[test]
    fn process_action_arrange_marriage() {
        let config = WorldConfig::default();
        let mut world = init_world(&config, [0x42; 32]);
        world.realms[0].owner_wallet = "player1".to_string();

        let chars: Vec<u32> = world.characters.iter()
            .filter(|c| c.faction == 0 && c.alive && c.is_adult() && c.spouse.is_none())
            .take(2)
            .map(|c| c.id)
            .collect();
        assert!(chars.len() >= 2, "Need at least 2 marriageable characters");

        let action = QueuedAction {
            wallet: "player1".to_string(),
            action: GameAction::ArrangeMarriage { a: chars[0], b: chars[1] },
            submitted_turn: 0,
        };
        let _ = process_action(&mut world, &action);
        assert_eq!(world.character(chars[0]).unwrap().spouse, Some(chars[1]));
        assert_eq!(world.character(chars[1]).unwrap().spouse, Some(chars[0]));
    }

    #[test]
    fn queue_action_processed_on_tick() {
        let config = WorldConfig::default();
        let mut world = init_world(&config, [0x42; 32]);
        world.realms[0].owner_wallet = "player1".to_string();

        queue_action(&mut world, "player1", GameAction::RaiseArmy { province: 7 });
        assert_eq!(world.action_queue.len(), 1);

        tick(&mut world, &[0x02; 32]);
        assert_eq!(world.action_queue.len(), 0, "Queue should be drained");
    }

    #[test]
    fn snapshot_returns_live_characters() {
        let config = WorldConfig::default();
        let world = init_world(&config, [0x42; 32]);
        let snap = snapshot_world(&world);

        assert_eq!(snap.turn, 0);
        assert_eq!(snap.provinces.len(), 25);
        assert_eq!(snap.factions.len(), 7);
        assert_eq!(snap.characters.len(), world.characters.iter().filter(|c| c.alive).count());
    }

    #[test]
    fn multiple_ticks_produce_valid_state() {
        let config = WorldConfig::default();
        let mut world = init_world(&config, [0x42; 32]);

        for i in 0u8..50 {
            let block = [i; 32];
            let summary = tick(&mut world, &block);
            assert_eq!(summary.turn, (i as u32) + 1);
            assert!(summary.active_factions > 0, "At least one faction should be alive");
            assert!(summary.total_population > 0, "Total population should be positive");
        }
    }

    #[test]
    fn world_serializes_with_bincode() {
        let config = WorldConfig::default();
        let world = init_world(&config, [0x42; 32]);
        let bytes = bincode::serialize(&world).expect("Failed to serialize");
        let restored: GameWorld = bincode::deserialize(&bytes).expect("Failed to deserialize");
        assert_eq!(restored.meta.turn, world.meta.turn);
        assert_eq!(restored.provinces.len(), world.provinces.len());
        assert_eq!(restored.characters.len(), world.characters.len());
    }

    #[test]
    fn visible_provinces_includes_owned_and_adjacent() {
        let config = WorldConfig::default();
        let world = init_world(&config, [0x42; 32]);

        let visible = visible_provinces(&world, 0);

        // Faction 0 controls some provinces; their neighbors should also be visible.
        let owned: Vec<u16> = world.provinces.iter()
            .filter(|p| p.controller == 0)
            .map(|p| p.id)
            .collect();

        for pid in &owned {
            assert!(visible.contains(pid),
                "Owned province {} should be visible", pid);
        }

        // Not all 25 provinces should be visible (fog hides distant ones).
        assert!(visible.len() < 25 || owned.len() >= 20,
            "Fog of war should hide some provinces (visible={}, owned={})",
            visible.len(), owned.len());
    }

    #[test]
    fn fog_snapshot_hides_distant_province_details() {
        let config = WorldConfig::default();
        let world = init_world(&config, [0x42; 32]);

        let full_snapshot = snapshot_world(&world);
        let fog_snapshot = snapshot_world_for_faction(&world, 0);

        // Same number of provinces (all included, just redacted).
        assert_eq!(fog_snapshot.provinces.len(), full_snapshot.provinces.len());

        // Some provinces should have zeroed population (fog).
        let hidden_count = fog_snapshot.provinces.iter()
            .filter(|p| p.population == 0 && p.controller != 0)
            .count();

        // Check that at least some non-owned provinces are hidden.
        let visible = visible_provinces(&world, 0);
        let non_visible_count = world.provinces.iter()
            .filter(|p| !visible.contains(&p.id))
            .count();

        if non_visible_count > 0 {
            assert!(hidden_count > 0,
                "Non-visible provinces should have hidden details");
        }
    }

    #[test]
    fn fog_snapshot_hides_armies_in_distant_provinces() {
        let config = WorldConfig::default();
        let mut world = init_world(&config, [0x42; 32]);

        // Place army in a province far from faction 0.
        let far_province = world.provinces.iter()
            .filter(|p| p.controller != 0)
            .last()
            .map(|p| p.id)
            .unwrap_or(24);

        let aid = world.alloc_army_id();
        world.armies.push(Army {
            id: aid,
            owner_faction: 4,
            commander: None,
            troops: Troops { levy: 500, men_at_arms: 100, knights: 10 },
            morale: FixedPoint::from_int(800),
            location: far_province,
            destination: None,
            movement_queue: Vec::new(),
            raised_turn: 0,
            supply: FixedPoint::from_int(100),
            siege: None,
        });

        let visible = visible_provinces(&world, 0);
        let fog_snapshot = snapshot_world_for_faction(&world, 0);

        if !visible.contains(&far_province) {
            // Army should not appear in fog snapshot.
            assert!(!fog_snapshot.armies.iter().any(|a| a.id == aid),
                "Army in non-visible province should be hidden");
        }
    }
}
