#!/bin/bash
#
# 🧅 Q-NarwhalKnight Tor Bridge Setup Script
#
# This script sets up the server-side Tor bridge for browser P2P connections.
# Run this on Server Beta (quillon.xyz) to enable mandatory Tor routing.
#
# Architecture:
# Browser → wss://quillon.xyz:9444/tor-bridge → websockify → Tor SOCKS5 → Tor Network
#
# Prerequisites:
# - Ubuntu/Debian server
# - nginx installed
# - Let's Encrypt SSL certificates for quillon.xyz
# - Root access
#
# Usage:
#   sudo ./setup-tor-bridge.sh
#

set -e

echo "🧅 Q-NarwhalKnight Tor Bridge Setup"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "❌ Please run as root (sudo ./setup-tor-bridge.sh)"
  exit 1
fi

# ============================================================================
# 1. Install Tor
# ============================================================================
echo "📦 Installing Tor..."

apt update
apt install -y tor

echo "✅ Tor installed"

# ============================================================================
# 2. Configure Tor
# ============================================================================
echo "⚙️ Configuring Tor..."

# Backup existing torrc
if [ -f /etc/tor/torrc ]; then
  cp /etc/tor/torrc /etc/tor/torrc.backup.$(date +%Y%m%d%H%M%S)
fi

# Create Tor configuration
cat > /etc/tor/torrc << 'EOF'
# Q-NarwhalKnight Tor Configuration
# Generated by setup-tor-bridge.sh

# SOCKS5 proxy for local applications (websockify)
SocksPort 9050
SocksPolicy accept 127.0.0.1
SocksPolicy reject *

# Hidden Service for Q-NarwhalKnight P2P
# This allows direct .onion connections
HiddenServiceDir /var/lib/tor/qnk_hidden_service/
HiddenServicePort 9001 127.0.0.1:9001

# Performance tuning
NumEntryGuards 3
CircuitBuildTimeout 60
LearnCircuitBuildTimeout 1

# Logging
Log notice file /var/log/tor/notices.log

# Don't run as exit node
ExitPolicy reject *:*
EOF

echo "✅ Tor configured"

# ============================================================================
# 3. Start Tor and get onion address
# ============================================================================
echo "🚀 Starting Tor service..."

systemctl enable tor
systemctl restart tor

# Wait for hidden service to be created
sleep 5

# Get onion address
if [ -f /var/lib/tor/qnk_hidden_service/hostname ]; then
  ONION_ADDRESS=$(cat /var/lib/tor/qnk_hidden_service/hostname)
  echo "✅ Tor hidden service address: $ONION_ADDRESS"
else
  echo "⚠️ Waiting for hidden service to be created..."
  sleep 10
  if [ -f /var/lib/tor/qnk_hidden_service/hostname ]; then
    ONION_ADDRESS=$(cat /var/lib/tor/qnk_hidden_service/hostname)
    echo "✅ Tor hidden service address: $ONION_ADDRESS"
  else
    echo "❌ Failed to create hidden service. Check Tor logs."
    exit 1
  fi
fi

# ============================================================================
# 4. Install websockify (WebSocket to SOCKS5 bridge)
# ============================================================================
echo "📦 Installing websockify..."

apt install -y python3-pip
pip3 install websockify

echo "✅ websockify installed"

# ============================================================================
# 5. Create websockify configuration
# ============================================================================
echo "⚙️ Creating websockify configuration..."

mkdir -p /etc/qnk-tor-bridge

cat > /etc/qnk-tor-bridge/config.json << 'EOF'
{
  "listen_host": "127.0.0.1",
  "listen_port": 9445,
  "socks_host": "127.0.0.1",
  "socks_port": 9050,
  "target_host": null,
  "target_port": null
}
EOF

echo "✅ websockify configured"

# ============================================================================
# 6. Create systemd service for websockify
# ============================================================================
echo "⚙️ Creating systemd service..."

cat > /etc/systemd/system/qnk-tor-bridge.service << 'EOF'
[Unit]
Description=Q-NarwhalKnight WebSocket-to-Tor Bridge
After=network.target tor.service
Requires=tor.service

[Service]
Type=simple
User=nobody
Group=nogroup

# websockify listens on 9445 and proxies to Tor SOCKS5 on 9050
ExecStart=/usr/local/bin/websockify 127.0.0.1:9445 --proxy-mode=socks5 --proxy-host=127.0.0.1:9050

Restart=always
RestartSec=5

# Security hardening
NoNewPrivileges=yes
PrivateTmp=yes

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable qnk-tor-bridge
systemctl start qnk-tor-bridge

echo "✅ systemd service created and started"

# ============================================================================
# 7. Configure nginx for Tor bridge
# ============================================================================
echo "⚙️ Configuring nginx..."

cat > /etc/nginx/sites-available/qnk-tor-bridge << 'EOF'
# Q-NarwhalKnight Tor Bridge WebSocket Endpoint
# Port 9444 - Dedicated Tor bridge for browser P2P

server {
    listen 9444 ssl;
    listen [::]:9444 ssl;
    server_name quillon.xyz;

    # SSL certificates (Let's Encrypt)
    ssl_certificate /etc/letsencrypt/live/quillon.xyz/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/quillon.xyz/privkey.pem;

    # SSL settings
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers off;

    # WebSocket upgrade for Tor bridge
    location /tor-bridge {
        proxy_pass http://127.0.0.1:9445;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Long timeout for Tor connections
        proxy_read_timeout 86400;
        proxy_send_timeout 86400;
        proxy_connect_timeout 60;
    }

    # Health check endpoint
    location /tor-ping {
        add_header Content-Type text/plain;
        return 200 'tor-bridge-ok';
    }

    # Root endpoint (info page)
    location / {
        add_header Content-Type text/plain;
        return 200 'Q-NarwhalKnight Tor Bridge - Port 9444\nConnect via WebSocket: wss://quillon.xyz:9444/tor-bridge';
    }
}
EOF

# Enable the site
ln -sf /etc/nginx/sites-available/qnk-tor-bridge /etc/nginx/sites-enabled/

# Test nginx configuration
nginx -t

# Reload nginx
systemctl reload nginx

echo "✅ nginx configured"

# ============================================================================
# 8. Open firewall port
# ============================================================================
echo "🔥 Configuring firewall..."

if command -v ufw &> /dev/null; then
  ufw allow 9444/tcp comment "Q-NarwhalKnight Tor Bridge"
  echo "✅ UFW rule added for port 9444"
fi

# ============================================================================
# 9. Print summary
# ============================================================================
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🧅 Tor Bridge Setup Complete!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📍 WebSocket Endpoint: wss://quillon.xyz:9444/tor-bridge"
echo "📍 Health Check: https://quillon.xyz:9444/tor-ping"
echo "📍 Onion Address: $ONION_ADDRESS"
echo ""
echo "📋 Services Status:"
systemctl status tor --no-pager -l | head -5
systemctl status qnk-tor-bridge --no-pager -l | head -5
echo ""
echo "📋 Update your browser config.ts with:"
echo "   BOOTSTRAP_PEERS = ["
echo "     '/dns4/quillon.xyz/tcp/9444/wss/p2p/12D3KooWFrhdwDDTgxPX41mUyRgLcE1ozsBYArKM4DT8t4VLwuNx',"
echo "   ]"
echo ""
echo "📋 Update torConfig.ts with onion address:"
echo "   onionBootstrap: '/onion3/${ONION_ADDRESS%.onion}:9001/p2p/12D3KooWFrhdwDDTgxPX41mUyRgLcE1ozsBYArKM4DT8t4VLwuNx',"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
