#!/bin/bash
# Q-NarwhalKnight 3-Node Network Test - Manual Version
# Tests transaction propagation with curl commands you can run

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║     Q-NarwhalKnight 3-Node Network Test (Manual)              ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "This script will show you the curl commands to run manually"
echo "to test transaction propagation across 3 nodes."
echo ""
echo "══════════════════════════════════════════════════════════════════"
echo "STEP 1: Create wallets on each node"
echo "══════════════════════════════════════════════════════════════════"
echo ""
echo "Node 1 (8091):"
echo 'curl -X POST http://localhost:8091/api/v1/wallets/create -H "Content-Type: application/json" -d '"'"'{"label": "Node1 Wallet"}'"'"' | jq -r '"'"'.data.address_formatted'"'"
echo ""
echo "Node 2 (8092):"
echo 'curl -X POST http://localhost:8092/api/v1/wallets/create -H "Content-Type: application/json" -d '"'"'{"label": "Node2 Wallet"}'"'"' | jq -r '"'"'.data.address_formatted'"'"
echo ""
echo "Node 3 (8093):"
echo 'curl -X POST http://localhost:8093/api/v1/wallets/create -H "Content-Type: application/json" -d '"'"'{"label": "Node3 Wallet"}'"'"' | jq -r '"'"'.data.address_formatted'"'"
echo ""
echo "══════════════════════════════════════════════════════════════════"
echo "STEP 2: Fund wallets (save the addresses from step 1)"
echo "══════════════════════════════════════════════════════════════════"
echo ""
echo 'curl -X POST http://localhost:8091/api/v1/faucet -H "Content-Type: application/json" -d '"'"'{"address": "YOUR_ADDRESS_1"}'"'"
echo 'curl -X POST http://localhost:8092/api/v1/faucet -H "Content-Type: application/json" -d '"'"'{"address": "YOUR_ADDRESS_2"}'"'"
echo 'curl -X POST http://localhost:8093/api/v1/faucet -H "Content-Type: application/json" -d '"'"'{"address": "YOUR_ADDRESS_3"}'"'"
echo ""
echo "══════════════════════════════════════════════════════════════════"
echo "STEP 3: Check balances"
echo "══════════════════════════════════════════════════════════════════"
echo ""
echo 'curl http://localhost:8091/api/v1/wallets/YOUR_ADDRESS_1/balance | jq '"'"'.data.balance_qug'"'"
echo ""
echo "══════════════════════════════════════════════════════════════════"
echo "STEP 4: Check P2P connectivity"
echo "══════════════════════════════════════════════════════════════════"
echo ""
echo "curl http://localhost:8091/api/v1/network/active-peers | jq '.'"
echo "curl http://localhost:8092/api/v1/network/active-peers | jq '.'"
echo "curl http://localhost:8093/api/v1/network/active-peers | jq '.'"
echo ""
echo "══════════════════════════════════════════════════════════════════"
echo "STEP 5: Send transaction from Node 1 to Node 2"
echo "══════════════════════════════════════════════════════════════════"
echo ""
echo 'curl -X POST http://localhost:8091/api/v1/transactions/send -H "Content-Type: application/json" -d '"'"'{
  "from": "YOUR_ADDRESS_1",
  "to": "YOUR_ADDRESS_2",
  "amount_qug": 10,
  "fee_qug": 0.1
}'"'"' | jq '"'"
echo ""
echo "══════════════════════════════════════════════════════════════════"
echo "Test started! Nodes are running on ports 8091, 8092, 8093"
echo "══════════════════════════════════════════════════════════════════"
