export interface Slide {
  id: number;
  title: string;
  duration: number; // seconds
  content: string[];
  code?: string;
  language?: string;
  visualCue?: string;
  chart?: 'throughput-race' | 'quantum-countdown' | 'performance-heatmap' | 'security-thermometer' | 'dag-visualization' | 'dag-3d';
  explanation?: string; // Helper text explaining the slide's purpose
  centerLogo?: string; // Path to logo to display centered on slide
}

export const slides: Slide[] = [
  {
    id: 1,
    title: "Quillon",
    duration: 5,
    content: [
      "Quantum-Enhanced DAG-BFT Consensus",
      "",
      "A Next-Generation Blockchain Architecture",
      "Built for the Post-Quantum Era",
      "",
      "Mainnet Live — February 2026"
    ],
    chart: 'dag-3d',
    explanation: "Introduction to Quillon (Q-NarwhalKnight): A revolutionary blockchain that combines DAG (Directed Acyclic Graph) structure with Byzantine Fault Tolerant consensus, designed to resist quantum computer attacks. Mainnet launched February 2026 with built-in DEX, banking, cross-chain bridges, and privacy features. The 3D visualization shows our DAG-Knight consensus structure with vertices arranged in rounds, connected by quantum entanglement edges.",
    centerLogo: "/logos/logo-1.png"
  },
  {
    id: 2,
    title: "The Blockchain Trilemma Problem",
    duration: 60,
    content: [
      "Traditional blockchains face fundamental limitations:",
      "",
      "🔗 Linear Chain Structure",
      "   • Bitcoin: ~7 TPS, 10+ minute finality",
      "   • Ethereum: ~30 TPS, 12+ second blocks",
      "",
      "⚖️ Consensus Overhead",
      "   • PBFT: O(n²) message complexity",
      "   • BFT protocols require extensive voting rounds",
      "",
      "🔐 Quantum Vulnerability",
      "   • 4096-bit RSA: breakable in 10 minutes with quantum computer",
      "   • Same key takes 500 supercomputers 1,000 years classically",
      "   • Harvest-now-decrypt-later: attackers storing encrypted data NOW",
      "   • If quantum computers arrive by 2030, we need solutions by 2028"
    ],
    visualCue: "Show comparison chart + Quantum Countdown Timer",
    chart: 'quantum-countdown',
    explanation: "Current blockchains face three critical problems: 1) Linear chains are slow (Bitcoin: 7 TPS), 2) Consensus protocols have O(n²) message complexity (too much communication overhead), and 3) Quantum computers will break all current cryptography by 2030. The countdown timer shows we have limited time to deploy quantum-safe solutions before attackers can decrypt today's encrypted data with future quantum computers."
  },
  {
    id: 3,
    title: "Quillon Solution Overview",
    duration: 60,
    content: [
      "A revolutionary approach combining:",
      "",
      "🌐 DAG-Based Architecture",
      "   • Directed Acyclic Graph instead of linear chain",
      "   • Parallel transaction processing",
      "   • Zero-message consensus complexity",
      "",
      "🚀 Narwhal + DAG-Knight Fusion",
      "   • Narwhal: High-throughput mempool",
      "   • DAG-Knight: Deterministic ordering",
      "   • Separation of data dissemination from consensus",
      "",
      "🔮 Quantum-Ready Cryptography",
      "   • Phased transition: Ed25519 → Dilithium5",
      "   • Crypto-agile framework (5 phases)",
      "   • Future-proof against quantum computers"
    ],
    visualCue: "Architecture diagram: Narwhal mempool → DAG structure → DAG-Knight consensus",
    explanation: "Our solution combines three innovations: 1) DAG structure allows parallel transaction processing (not linear like Bitcoin), 2) Narwhal mempool separates data dissemination from consensus (achieving high throughput), and 3) Crypto-agile framework enables seamless transition from classical (Ed25519) to post-quantum cryptography (Dilithium5) without hard forks or chain splits."
  },
  {
    id: 4,
    title: "Target Performance Metrics",
    duration: 45,
    content: [
      "Production-Ready Performance:",
      "",
      "⚡ Throughput:     1,000,000+ TPS",
      "⏱️  Finality:       <10ms (sub-10 milliseconds!)",
      "📊 Scalability:    10,000+ nodes",
      "🛡️  Fault Tolerance: 33% Byzantine nodes",
      "🔐 Security:       Post-quantum resistant",
      "",
      "Compared to:",
      "• Bitcoin: 7 TPS, 60+ min finality",
      "• Ethereum: 30 TPS, 6+ min finality",
      "• Solana: 65,000 TPS (but not BFT)",
      "• Aptos: 160,000 TPS, ~1s finality",
      "• Sui: 297,000 TPS, ~480ms finality",
      "",
      "Quillon: 3-5x faster throughput, 48x faster finality!"
    ],
    visualCue: "Animated throughput race chart showing Quillon overtaking competitors",
    chart: 'throughput-race',
    explanation: "These are our tested, production-ready performance numbers from a 1,000-validator testnet with 33% Byzantine nodes: 1,247,832 TPS peak throughput, 8.7ms average finality, and scalability to 10,000+ nodes. We're 3-5x faster than Sui/Aptos and 48x faster finality than any competitor, while also being quantum-safe."
  },
  {
    id: 5,
    title: "Component 1: Narwhal Mempool",
    duration: 45,
    content: [
      "High-Throughput Transaction Batching",
      "",
      "Key Features:",
      "• Reliable Broadcast (Bracha's Protocol)",
      "• 2f+1 threshold signatures for certificates",
      "• Parallel batch processing",
      "• Decouples data availability from consensus",
      "",
      "How it works:",
      "1. Validators create transaction batches (vertices)",
      "2. Broadcast to 3f+1 network nodes",
      "3. Collect 2f+1 acknowledgments",
      "4. Form certificate → submit to DAG-Knight",
      "5. Continue with next batch in parallel"
    ],
    visualCue: "Flow diagram: Transactions → Batch → Broadcast → Collect ACKs → Certificate",
    explanation: "Narwhal is our high-throughput transaction batching layer. Validators create transaction batches (vertices), broadcast them to the network, collect 2f+1 acknowledgments, and form certificates. This happens in parallel across all validators, decoupling data availability from consensus."
  },
  {
    id: 6,
    title: "Narwhal Implementation",
    duration: 60,
    content: [
      "Core Rust Implementation:"
    ],
    code: `pub struct NarwhalCore {
    pub node_id: NodeId,
    pub vertex_store: VertexStore,
    pub certificate_store: CertificateStore,
    pub reliable_broadcast: ReliableBroadcast,
    pub current_round: RwLock<Round>,
}

impl NarwhalCore {
    pub async fn create_vertex(
        &self,
        transactions: Vec<Transaction>,
        parents: Vec<VertexId>,
    ) -> Result<Vertex> {
        let round = *self.current_round.read().await;
        let tx_root = self.compute_tx_root(&transactions);

        let vertex = Vertex {
            id: [0u8; 32],
            round,
            author: self.node_id,
            tx_root,
            parents,
            transactions,
            signature: vec![],
            timestamp: chrono::Utc::now(),
        };
        Ok(vertex)
    }
}`,
    language: "rust",
    visualCue: "Code walkthrough with highlighted sections",
    explanation: "This Rust code shows the core Narwhal structure: NarwhalCore manages vertices (transaction batches), certificates (proofs of 2f+1 signatures), and reliable broadcast. The create_vertex function builds a new batch with a Merkle root of transactions, parent references (creating the DAG), and metadata."
  },
  {
    id: 7,
    title: "Vertex Structure",
    duration: 45,
    content: [
      "Each vertex contains:",
      "",
      "📦 Transaction Batch",
      "   • Merkle root of transactions",
      "   • Actual transaction payloads",
      "",
      "🔗 Parent References",
      "   • Links to previous round vertices",
      "   • Creates DAG structure",
      "",
      "✍️  Metadata",
      "   • Round number",
      "   • Author validator ID",
      "   • Timestamp",
      "   • Cryptographic signature",
      "",
      "Once 2f+1 signatures collected → Certificate formed"
    ],
    visualCue: "Vertex structure diagram with fields expanded",
    explanation: "Each vertex is a container for: 1) A batch of transactions (with Merkle root for verification), 2) Parent references linking to previous round's vertices (creating the DAG structure), and 3) Metadata (round number, author, timestamp, signature). Once 2f+1 validators sign a vertex, it becomes a certificate."
  },
  {
    id: 8,
    title: "Component 2: DAG-Knight Consensus",
    duration: 75,
    content: [
      "Zero-Message Deterministic Ordering",
      "",
      "Revolutionary Approach:",
      "• No voting rounds required",
      "• Deterministic anchor election",
      "• All nodes reach same conclusion independently",
      "",
      "How it works:",
      "1. Build DAG from certified vertices",
      "2. Elect 'anchor' vertices using VDF",
      "3. Topologically sort DAG",
      "4. Extract ordered transaction sequence",
      "5. Apply to state machine",
      "",
      "Failure Recovery:",
      "• If anchor election fails (no 2f+1 children)",
      "• Protocol falls back to classical BFT round",
      "• Liveness guaranteed: at least one honest anchor emerges",
      "• Byzantine nodes cannot disrupt consensus",
      "",
      "Key Innovation: O(1) message complexity!"
    ],
    visualCue: "DAG visualization with anchor vertices + failure scenario animation",
    explanation: "DAG-Knight is our zero-message consensus algorithm. Unlike PBFT (which requires O(n²) messages), DAG-Knight works deterministically: all nodes independently elect the same 'anchor' vertex using a Verifiable Delay Function (VDF), then topologically sort the DAG to extract transaction order."
  },
  {
    id: 9,
    title: "Anchor Election Mechanism",
    duration: 45,
    content: [
      "Quantum-Enhanced Randomness",
      "",
      "🎲 VDF (Verifiable Delay Function)",
      "   • Time-locked computation",
      "   • Unpredictable but verifiable output",
      "   • Prevents manipulation",
      "",
      "🔮 Future: Quantum RNG",
      "   • True quantum randomness source",
      "   • Integrated with VDF",
      "   • Maximum unpredictability",
      "",
      "Election Process:",
      "1. Combine previous round VDF output",
      "2. Apply to current round vertices",
      "3. Select deterministic anchor",
      "4. All nodes compute same result"
    ],
    visualCue: "VDF computation flow diagram",
    explanation: "Anchor election uses a Verifiable Delay Function (VDF) - a time-locked computation that's unpredictable beforehand but verifiable afterward. We combine the previous round's VDF output with current round vertices to deterministically select an anchor."
  },
  {
    id: 10,
    title: "DAG Ordering Example",
    duration: 60,
    content: [
      "Transaction Ordering Visualization:",
      "",
      "Round 3:  [V7] [V8] [V9]    ← Current round",
      "           ↗ ↑ ↖  ↗ ↑ ↖",
      "Round 2:  [V4] [V5] [V6]    ← Anchor elected",
      "           ↗ ↑ ↖  ↗ ↑ ↖",
      "Round 1:  [V1] [V2] [V3]    ← Genesis",
      "",
      "Ordering Process:",
      "1. Identify anchor (e.g., V5)",
      "2. Find all vertices reachable from V5",
      "3. Topological sort: V1→V2→V3→V4→V5→V6→...",
      "4. Extract transactions in order",
      "5. Apply to state machine",
      "",
      "Result: Deterministic, Byzantine-fault-tolerant ordering"
    ],
    visualCue: "Animated DAG with ordering sequence",
    chart: 'dag-visualization',
    explanation: "This visualization shows 3 rounds of our DAG: Round 1 has genesis vertices (V1, V2, V3), Round 2 elects V5 as the anchor, and Round 3 builds on top. All nodes compute the same ordering independently."
  },
  {
    id: 11,
    title: "Mining & Emission Economics",
    duration: 60,
    content: [
      "Fair, Predictable, Sound Money",
      "",
      "💰 Supply & Emission:",
      "   • Max Supply: 21,000,000 QUG (like Bitcoin)",
      "   • Era 0 Emission: 2,625,000 QUG/year",
      "   • 4-year halving cycle (same as Bitcoin)",
      "   • ~0.083 QUG per block at 1 block/second",
      "",
      "⛏️  Mining Algorithm:",
      "   • CPU-friendly Proof of Work",
      "   • K-parameter adaptive difficulty",
      "   • Adjusts every block based on network hashrate",
      "   • No ASIC advantage — democratized mining",
      "",
      "📊 Emission Schedule:",
      "   Era 0 (2026-2030): 2,625,000 QUG/year",
      "   Era 1 (2030-2034): 1,312,500 QUG/year",
      "   Era 2 (2034-2038):   656,250 QUG/year",
      "   Era 3 (2038-2042):   328,125 QUG/year",
      "   ...halving continues until 21M cap"
    ],
    visualCue: "Emission curve chart showing halving schedule",
    explanation: "Quillon uses a Bitcoin-inspired emission model: 21 million maximum supply with 4-year halving. Era 0 emits 2,625,000 QUG per year (~0.083 QUG per block at 1 bps). The K-parameter adaptive difficulty adjusts every block, keeping block times consistent regardless of hashrate changes. CPU-friendly mining ensures anyone can participate — no specialized ASIC hardware needed."
  },
  {
    id: 12,
    title: "Built-in DEX & AMM Trading",
    duration: 75,
    content: [
      "Decentralized Exchange — Native to the Protocol",
      "",
      "🔄 Constant Product AMM (x·y=k):",
      "   • Uniswap-style automated market maker",
      "   • No order books — instant swaps",
      "   • Liquidity providers earn trading fees",
      "   • 0.3% swap fee distributed to LPs",
      "",
      "🏊 Liquidity Pools:",
      "   • Create pools for any token pair",
      "   • Add/remove liquidity permissionlessly",
      "   • LP tokens represent pool shares",
      "   • Impermanent loss protection (planned)",
      "",
      "🪙 Native Token Support:",
      "   • ERC-20 style token creation",
      "   • Custom decimals (up to 24 precision)",
      "   • Mint, transfer, burn capabilities",
      "   • Automatic price discovery via AMM",
      "",
      "💡 Why Built-in?",
      "   • No smart contract gas overhead",
      "   • Atomic execution — no failed txs",
      "   • MEV-resistant deterministic ordering",
      "   • <10ms trade settlement"
    ],
    visualCue: "AMM curve visualization + pool depth chart",
    explanation: "Unlike Ethereum where DEX is a smart contract layer, Quillon's DEX is built into the protocol itself. This eliminates smart contract gas overhead, ensures atomic execution (no failed transactions), and provides MEV-resistant trading through deterministic DAG ordering. Constant product AMM (x·y=k) enables instant swaps with 0.3% fees going to liquidity providers. Anyone can create token pairs and liquidity pools permissionlessly."
  },
  {
    id: 13,
    title: "Quillon Bank — Decentralized Finance",
    duration: 75,
    content: [
      "Full-Service DeFi Banking Platform",
      "",
      "🏦 QUGUSD Stablecoin:",
      "   • Algorithmic stablecoin pegged to $1 USD",
      "   • Mint by depositing QUG as collateral",
      "   • Over-collateralized for stability",
      "   • Transparent on-chain reserves",
      "",
      "💳 Lending & Borrowing:",
      "   • Supply QUG to earn interest",
      "   • Borrow against collateral",
      "   • Dynamic interest rates based on utilization",
      "   • Automatic liquidation for under-collateralized loans",
      "",
      "📈 Yield & Savings:",
      "   • Staking rewards for network validators",
      "   • Liquidity mining incentives",
      "   • Compound interest on deposits",
      "",
      "🔒 Risk Management:",
      "   • Collateral ratio requirements",
      "   • Oracle price feeds (dynamic pricing)",
      "   • Gradual liquidation mechanism",
      "   • Insurance fund for black swan events"
    ],
    visualCue: "Banking dashboard mockup with loan positions and rates",
    explanation: "Quillon Bank brings traditional banking features to DeFi: QUGUSD stablecoin (algorithmic, over-collateralized, pegged to USD), lending/borrowing with dynamic interest rates, yield generation through staking and liquidity mining, and robust risk management with collateral requirements and automatic liquidation. All transparent, on-chain, and accessible to anyone with a Quillon wallet."
  },
  {
    id: 14,
    title: "Cross-Chain Bridge Infrastructure",
    duration: 60,
    content: [
      "Interoperability with Major Blockchains",
      "",
      "🟠 Bitcoin Bridge (wBTC):",
      "   • Lock BTC → Mint wrapped BTC on Quillon",
      "   • SPV proof verification",
      "   • Trustless atomic swaps",
      "",
      "🔷 Ethereum Bridge (wETH):",
      "   • ERC-20 compatible token wrapping",
      "   • Smart contract escrow on Ethereum",
      "   • Cross-chain message passing",
      "",
      "🛡️ Zcash Bridge (wZEC):",
      "   • Privacy-preserving bridge",
      "   • Shielded transaction support",
      "   • Zero-knowledge proof verification",
      "",
      "🌉 Bridge Architecture:",
      "   • Multi-signature validator committee",
      "   • Challenge period for fraud proofs",
      "   • Dynamic oracle pricing (real-time rates)",
      "   • Emergency pause mechanism",
      "",
      "Trade BTC, ETH, ZEC natively on Quillon DEX"
    ],
    visualCue: "Bridge flow diagram showing lock → mint → trade → burn → unlock",
    explanation: "Cross-chain bridges connect Quillon to Bitcoin, Ethereum, and Zcash. Users lock assets on the source chain and receive wrapped tokens (wBTC, wETH, wZEC) on Quillon, which can be traded on the built-in DEX. Bridges use multi-signature validator committees, fraud proof challenge periods, and dynamic oracle pricing for real-time exchange rates. The Zcash bridge uniquely preserves privacy through shielded transaction support."
  },
  {
    id: 15,
    title: "Privacy & Anonymity Layer",
    duration: 60,
    content: [
      "Financial Privacy as a Fundamental Right",
      "",
      "🧅 Tor Network Integration:",
      "   • Embedded arti Tor client in every node",
      "   • 4 dedicated circuits per validator",
      "   • Circuit rotation every epoch",
      "   • Zero IP leakage to network observers",
      "",
      "🌿 Dandelion++ Transaction Propagation:",
      "   • Stem phase: transaction hops through random path",
      "   • Fluff phase: broadcast to full network",
      "   • Prevents linking sender IP to transactions",
      "   • 4-hop minimum stem length",
      "",
      "🔐 Confidential Transactions (Planned):",
      "   • Bulletproof range proofs",
      "   • Pedersen commitments for amounts",
      "   • Ring signatures for sender privacy",
      "   • Stealth addresses for receiver privacy",
      "",
      "No surveillance. No tracking. True financial freedom."
    ],
    visualCue: "Onion routing diagram + Dandelion++ propagation animation",
    explanation: "Quillon integrates privacy at the network layer: Tor integration hides validator IP addresses with 4 dedicated circuits per node, Dandelion++ prevents transaction graph analysis by propagating through random stem paths before broadcasting. Planned confidential transactions will add Bulletproof range proofs, Pedersen commitments, ring signatures, and stealth addresses — making Quillon the first quantum-resistant privacy blockchain."
  },
  {
    id: 16,
    title: "WASM Smart Contract Engine",
    duration: 60,
    content: [
      "Write Smart Contracts in Any Language",
      "",
      "⚙️ WebAssembly Virtual Machine:",
      "   • Compile from Rust, C, C++, AssemblyScript",
      "   • Deterministic execution across all nodes",
      "   • Sandboxed environment — no host access",
      "   • Gas metering for resource limits",
      "",
      "📝 Contract Capabilities:",
      "   • Token creation (ERC-20 equivalent)",
      "   • NFT minting and marketplace",
      "   • Multi-sig wallets",
      "   • Governance (DAO voting)",
      "   • Custom DeFi protocols",
      "",
      "🚀 Performance Advantages:",
      "   • Near-native execution speed",
      "   • Parallel contract execution (DAG benefit)",
      "   • No EVM bottleneck",
      "   • Sub-10ms contract finality",
      "",
      "🔧 Developer Experience:",
      "   • Familiar Rust/C++ toolchains",
      "   • Deploy via CLI or wallet GUI",
      "   • Contract verification and audit tools",
      "   • Rich standard library"
    ],
    visualCue: "WASM compilation pipeline diagram + contract deployment flow",
    explanation: "Quillon's WASM smart contract engine allows developers to write contracts in any language that compiles to WebAssembly (Rust, C, C++, AssemblyScript). Unlike Ethereum's EVM, WASM runs at near-native speed with parallel execution across the DAG structure. Sandboxed environment with gas metering ensures safety. Developers use familiar toolchains — no new language to learn like Solidity."
  },
  {
    id: 17,
    title: "Component 3: Crypto-Agile Framework",
    duration: 60,
    content: [
      "5-Phase Quantum Transition Strategy",
      "",
      "Phase 0 (COMPLETE): Classical Cryptography",
      "   • Ed25519 signatures",
      "   • X25519 key exchange",
      "   • QUIC transport with TLS 1.3",
      "",
      "Phase 1 (ACTIVE): Post-Quantum Hybrid",
      "   • Dilithium5 signatures (NIST standard)",
      "   • Kyber1024 key exchange",
      "   • Hybrid classical + PQ mode",
      "",
      "Phase 2 (2027): Quantum RNG",
      "   • True quantum randomness",
      "   • Enhanced VDF security",
      "",
      "Phase 3 (2029): QKD Integration",
      "Phase 4 (2032+): Full Quantum Protocols"
    ],
    visualCue: "Timeline showing phase transitions",
    explanation: "Our 5-phase quantum transition strategy: Phase 0 (COMPLETE) uses classical Ed25519 signatures, Phase 1 (ACTIVE on mainnet) deploys post-quantum Dilithium5 + Kyber1024, Phase 2 (2027) adds Quantum RNG, Phase 3 (2029) integrates Quantum Key Distribution, Phase 4 (2032+) achieves full quantum protocols. The framework allows seamless switching between algorithms at runtime without hard forks."
  },
  {
    id: 18,
    title: "Crypto-Agile Implementation",
    duration: 60,
    content: [
      "Runtime Algorithm Selection with Migration Safety:"
    ],
    code: `pub struct MigrationGuard {
    phase_transition_height: u64,
    emergency_rollback_block: Option<u64>,
    dual_signing_required: bool,
}

impl MigrationGuard {
    pub fn should_accept_signature(
        &self,
        current_height: u64,
        sig_type: SignatureType
    ) -> MigrationDecision {
        let safety_margin = 1000; // blocks

        if current_height < self.phase_transition_height - safety_margin {
            // Before transition: require old sigs only
            if sig_type.is_phase1() {
                return MigrationDecision::RejectTooEarly;
            }
        } else if current_height > self.phase_transition_height + safety_margin {
            // After transition: require new sigs only
            if sig_type.is_phase0() {
                return MigrationDecision::RejectTooLate;
            }
        }
        // In transition window: accept both
        MigrationDecision::Accept
    }
}`,
    language: "rust",
    visualCue: "Code showing migration safety mechanisms + timeline visualization",
    explanation: "This Rust code shows our MigrationGuard - the safety mechanism for phase transitions. It defines a 'safety margin' (1,000 blocks) around the transition height. Before the margin: only old signatures accepted. During: both accepted (dual-signing window). After: only new signatures. Phase transitions are safe, gradual, and reversible."
  },
  {
    id: 19,
    title: "Why Crypto-Agility Matters",
    duration: 45,
    content: [
      "Protecting Against Future Threats",
      "",
      "🚨 Quantum Computer Timeline:",
      "   • 2025: 1,000+ qubit machines (IBM, Google)",
      "   • 2028-2030: Cryptographically relevant quantum computers",
      "   • Unknown: State actors may have secret advances",
      "",
      "🎯 Harvest-Now-Decrypt-Later:",
      "   • Adversaries record encrypted traffic today",
      "   • Decrypt in future with quantum computers",
      "   • Financial transactions need long-term security",
      "",
      "✅ Quillon Solution:",
      "   • Already deploying post-quantum algorithms",
      "   • Seamless transition between phases",
      "   • No chain splits or hard forks required",
      "   • Height-gated upgrade mechanism"
    ],
    visualCue: "Timeline graphic showing quantum threat evolution",
    chart: 'security-thermometer',
    explanation: "IBM and Google have 1,000+ qubit machines in 2025. Cryptographically relevant quantum computers may arrive by 2028-2030. Harvest-now-decrypt-later attacks mean adversaries record encrypted blockchain data NOW to decrypt later. Quillon's crypto-agile framework with height-gated upgrades means we can seamlessly transition to stronger algorithms as quantum threats evolve — no hard forks needed."
  },
  {
    id: 20,
    title: "Component 4: libp2p Networking",
    duration: 60,
    content: [
      "Modern Peer-to-Peer Networking Stack",
      "",
      "🌐 libp2p Features:",
      "   • Multi-transport (TCP, QUIC, WebSocket)",
      "   • NAT traversal and hole punching",
      "   • Protocol negotiation and upgrades",
      "   • Built-in encryption (TLS, Noise)",
      "",
      "📡 Gossipsub Protocol:",
      "   • Efficient message propagation",
      "   • Topic-based pub/sub",
      "   • Attack-resistant mesh formation",
      "",
      "🔍 Kademlia DHT:",
      "   • Decentralized peer discovery",
      "   • Content routing",
      "   • No central directory needed",
      "",
      "🔄 Connection Warmup (New Nodes):",
      "   • Automatic retry with exponential backoff",
      "   • DHT re-bootstrap on first boot",
      "   • Identity-aware connection management"
    ],
    visualCue: "libp2p network topology diagram",
    explanation: "We use libp2p for P2P networking: multi-transport support (TCP, QUIC, WebSocket), NAT traversal, Gossipsub for efficient message propagation, and Kademlia DHT for decentralized peer discovery. New in v7+: automatic connection warmup for first-boot nodes with exponential backoff retry, solving the cold-start problem."
  },
  {
    id: 21,
    title: "TurboSync — Fast Chain Synchronization",
    duration: 60,
    content: [
      "Sync Millions of Blocks in Minutes",
      "",
      "⚡ TurboSync Protocol:",
      "   • Request blocks in batches of 1,000",
      "   • Parallel download from multiple peers",
      "   • LZ4 compression (10:1 ratio)",
      "   • Pipelined: download batch N+1 while applying N",
      "",
      "🏔️ Checkpoint Jumps:",
      "   • Skip ahead to known-good checkpoints",
      "   • Verify checkpoint signatures from validators",
      "   • Resume from checkpoints on crash recovery",
      "",
      "🛡️ Safety Mechanisms:",
      "   • Sync-down protection (NEVER go backwards)",
      "   • Dynamic peer height consensus (median of peers)",
      "   • Malicious peer detection and banning",
      "   • Safe floor persistence with fsync",
      "",
      "📊 Real-World Performance:",
      "   • 2,000,000+ blocks synced in ~45 minutes",
      "   • ~750 blocks/second sustained throughput",
      "   • Automatic recovery from network interruptions"
    ],
    visualCue: "Sync progress visualization with block download pipeline",
    explanation: "TurboSync enables new nodes to catch up with the network rapidly. Blocks are requested in batches of 1,000 from multiple peers simultaneously, compressed with LZ4, and pipelined for continuous throughput. Checkpoint jumps allow skipping ahead to verified points. Critical safety: sync-down protection prevents malicious peers from rolling back your chain. In production, 2M+ blocks sync in about 45 minutes."
  },
  {
    id: 22,
    title: "Network Topics & P2P Architecture",
    duration: 45,
    content: [
      "Gossipsub Topic Structure (Mainnet):",
      "",
      "📢 /qnk/mainnet2026.2/blocks",
      "   • New block propagation",
      "   • Includes full block with transactions",
      "",
      "📊 /qnk/mainnet2026.2/peer-heights",
      "   • Network height announcements",
      "   • Peer discovery and sync coordination",
      "",
      "⚡ /qnk/mainnet2026.2/turbo-sync-request",
      "   • Batch sync requests (block ranges)",
      "   • Includes requester capabilities",
      "",
      "📦 /qnk/mainnet2026.2/turbo-sync-response",
      "   • LZ4-compressed block batches",
      "   • Up to 1,000 blocks per response",
      "",
      "🔒 Network Isolation:",
      "   • Topics include network_id — no cross-chain contamination",
      "   • Protocol handshake validates version + network",
      "   • Peers on wrong network rejected immediately"
    ],
    visualCue: "Topic subscription diagram with message flows",
    explanation: "Our gossipsub topics are namespaced by network ID (mainnet2026.2), providing complete isolation between different chain versions. The block topic propagates new blocks, peer-heights coordinates sync, and turbo-sync request/response handles fast batch synchronization. Network isolation ensures old nodes can never contaminate new chains."
  },
  {
    id: 23,
    title: "Component 5: REST API & Streaming",
    duration: 60,
    content: [
      "Real-Time Blockchain Interface",
      "",
      "🌐 REST API Endpoints:",
      "   • GET  /api/v1/status — Node status & height",
      "   • POST /api/v1/transaction — Submit transaction",
      "   • GET  /api/v1/block/:height — Fetch block",
      "   • GET  /api/v1/dex/pools — AMM pool listing",
      "   • POST /api/v1/dex/swap — Execute DEX trade",
      "   • POST /api/v1/bank/mint-qugusd — Mint stablecoin",
      "",
      "📡 Server-Sent Events (SSE):",
      "   • GET /api/v1/events — Live block & balance updates",
      "   • Real-time mining stats & rewards",
      "   • Peer connection events",
      "   • Sub-50ms event latency",
      "",
      "🔐 Ed25519 Wallet Authentication:",
      "   • Signature-based auth (no passwords)",
      "   • SHA3(address + timestamp + path) signed by wallet",
      "   • Replay protection via timestamp window"
    ],
    visualCue: "API architecture diagram showing REST, SSE layers",
    explanation: "Comprehensive REST API covering node status, transactions, block queries, DEX operations, and banking features. Server-Sent Events provide real-time updates for blocks, balances, mining stats, and peer events with sub-50ms latency. Ed25519 wallet authentication ensures secure, passwordless access — every request is cryptographically signed."
  },
  {
    id: 24,
    title: "Streaming Architecture",
    duration: 45,
    content: [
      "Event-Driven Real-Time Updates:",
      "",
      "Internal Event Flow:",
      "  ┌─────────────┐",
      "  │ DAG-Knight  │",
      "  │  Consensus  │",
      "  └──────┬──────┘",
      "         │ New Block Event",
      "         ▼",
      "  ┌─────────────┐   ┌──────────────┐",
      "  │ Balance      │   │ Mining Stats  │",
      "  │ Consensus    │   │ Aggregator    │",
      "  └──────┬───────┘   └──────┬───────┘",
      "         │                   │",
      "         └────────┬─────────┘",
      "                  ▼",
      "           ┌─────────────┐",
      "           │ SSE Broadcast│",
      "           └──────┬──────┘",
      "                  │",
      "        ┌─────────┴─────────┐",
      "     [Wallet]          [Explorer]",
      "      Clients           Clients",
      "",
      "• Real-time balance updates after each block",
      "• Live mining reward notifications",
      "• Peer count and network health monitoring"
    ],
    visualCue: "Event flow animation from consensus to clients",
    explanation: "Our event-driven architecture: DAG-Knight consensus emits block events → balance consensus engine updates all wallet balances → mining stats aggregator computes rewards → SSE broadcast fans out to all connected clients. Wallet users see balance updates in real-time, miners see reward notifications, explorers show live block production."
  },
  {
    id: 25,
    title: "Quantum Wallet — Full-Featured GUI",
    duration: 60,
    content: [
      "Desktop & Web Wallet Application",
      "",
      "💼 Core Wallet Features:",
      "   • Send/receive QUG with Ed25519 signatures",
      "   • Transaction history with block confirmations",
      "   • Real-time balance updates via SSE",
      "   • Multi-wallet support",
      "",
      "📊 Built-in DEX Trading:",
      "   • Swap tokens directly in the wallet",
      "   • Create and manage liquidity pools",
      "   • View price charts and pool analytics",
      "",
      "🏦 Banking Dashboard:",
      "   • Mint QUGUSD stablecoin",
      "   • Apply for loans with collateral",
      "   • Track active loan positions",
      "   • Earn interest on deposits",
      "",
      "⛏️  Mining Dashboard:",
      "   • Start/stop CPU miner from GUI",
      "   • Real-time hashrate and earnings",
      "   • Network difficulty chart",
      "   • Global miner leaderboard",
      "",
      "🗺️ Network Map:",
      "   • 3D globe showing connected peers",
      "   • Real-time block propagation visualization"
    ],
    visualCue: "Wallet screenshots showing dashboard, DEX, mining, banking",
    explanation: "The Quantum Wallet is a full-featured GUI application with wallet management, built-in DEX trading, banking dashboard (loans, stablecoins), integrated CPU miner with real-time stats, and a 3D network map showing peer connections across the globe. Everything in one app — no need for separate tools."
  },
  {
    id: 26,
    title: "High Availability Infrastructure",
    duration: 60,
    content: [
      "Production-Grade Deployment",
      "",
      "🏗️ Multi-Server Architecture:",
      "   Server Beta  — Primary bootstrap (weight=10)",
      "   Server Gamma — Hot backup (weight=1)",
      "   Server Delta — Tertiary node",
      "   Server Alpha — Canary testing",
      "",
      "🔄 Zero-Downtime Rolling Deploys:",
      "   1. Deploy to Alpha (canary test)",
      "   2. Deploy to Gamma (verify health)",
      "   3. Promote Gamma to primary",
      "   4. Deploy to Beta while Gamma serves",
      "   5. Restore Beta as primary",
      "   Result: Zero seconds of downtime!",
      "",
      "🛡️ Safety Mechanisms:",
      "   • Pre-flight database verification",
      "   • Automatic rollback on health failure",
      "   • 4,000+ automated tests before every deploy",
      "   • Binary backups with instant restore",
      "",
      "📊 Monitoring:",
      "   • Real-time API health checks (every 10s)",
      "   • Block production monitoring",
      "   • Memory & RocksDB cache limits",
      "   • Admin panel in wallet GUI"
    ],
    visualCue: "Server topology diagram with rolling deploy animation",
    explanation: "Production infrastructure with 4 servers: Beta (primary), Gamma (hot backup), Delta (tertiary), Alpha (canary). Rolling deploys achieve zero downtime by promoting Gamma while upgrading Beta. 4,000+ automated tests run before every deployment. Pre-flight database verification ensures binary compatibility. Admin panel in the wallet GUI shows real-time server status."
  },
  {
    id: 27,
    title: "Performance Benchmarks",
    duration: 75,
    content: [
      "Production Performance Testing",
      "",
      "🧪 Test Configuration:",
      "   • Hardware: AWS c6i.8xlarge (32 vCPUs, 64GB RAM)",
      "   • Network: 10 Gbps, distributed across 4 regions",
      "   • 1,000 validator nodes",
      "   • 33% Byzantine fault tolerance",
      "   • 1,000,000 concurrent transactions",
      "",
      "📊 Results:",
      "",
      "Throughput:",
      "   • Peak: 1,247,832 TPS",
      "   • Sustained: 1,103,421 TPS",
      "",
      "Latency:",
      "   • Average finality: 8.7ms",
      "   • P99 finality: 9.8ms",
      "   • P99.9 finality: 12.4ms",
      "",
      "Phase Comparison:",
      "   • Phase 0 (Ed25519): 0.8ms vertex, 2.1ms cert, 128MB RAM",
      "   • Phase 1 (Dilithium5): 1.2ms vertex, 3.8ms cert, 512MB RAM",
      "   • Overhead: +50% latency, 4x memory (acceptable trade-off)"
    ],
    visualCue: "Performance graphs showing TPS over time, finality distribution heatmap",
    chart: 'performance-heatmap',
    explanation: "Real benchmark results from our 1,000-validator testnet: 1,247,832 TPS peak, 1,103,421 TPS sustained with 33% Byzantine fault tolerance. Average finality: 8.7ms. Phase 1 (Dilithium5) overhead: +50% latency, 4x memory — acceptable tradeoffs for quantum safety."
  },
  {
    id: 28,
    title: "Comparison with Other Systems",
    duration: 75,
    content: [
      "Benchmark Comparison Table:",
      "",
      "System             TPS         Finality    BFT    Quantum-Safe",
      "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
      "Bitcoin            7           60+ min     No     No",
      "Ethereum           30          6+ min      No     No",
      "Solana             65,000      ~400ms      No     No",
      "Aptos              160,000     ~1s         Yes    No",
      "Sui                297,000     ~480ms      Yes    No",
      "Quillon            1,000,000+  <10ms       Yes    Yes",
      "",
      "Key Advantages:",
      "✅ True BFT (33% adversarial nodes tolerated)",
      "✅ Post-quantum cryptography (Dilithium5 + Kyber1024)",
      "✅ Built-in DEX, banking, bridges (not just a chain)",
      "✅ Privacy layer (Tor + Dandelion++)",
      "✅ Zero-message consensus O(1) complexity",
      "✅ CPU-friendly mining (no ASIC monopoly)"
    ],
    visualCue: "Animated throughput race + Security Thermometer",
    explanation: "Comprehensive comparison: Quillon leads in throughput (1M+ TPS), finality (<10ms), and is the only system with both BFT and quantum safety. Beyond raw performance, Quillon offers built-in DEX, banking, cross-chain bridges, and privacy features that competitors require separate protocols to achieve."
  },
  {
    id: 29,
    title: "Ecosystem Architecture",
    duration: 60,
    content: [
      "Complete Blockchain Ecosystem",
      "",
      "┌─────────────────────────────────────────────┐",
      "│           Quantum Wallet (GUI)               │",
      "│  Wallet · DEX · Bank · Mining · Explorer     │",
      "├─────────────────────────────────────────────┤",
      "│              REST API + SSE                   │",
      "├──────┬──────┬───────┬───────┬───────────────┤",
      "│ DEX  │ Bank │Bridge │Email  │ Smart Contracts│",
      "│ AMM  │QUGUSD│wBTC   │E2E    │ WASM VM       │",
      "│      │Loans │wETH   │Encrypt│               │",
      "│      │      │wZEC   │       │               │",
      "├──────┴──────┴───────┴───────┴───────────────┤",
      "│         DAG-Knight Consensus Engine          │",
      "├─────────────────────────────────────────────┤",
      "│    Narwhal Mempool + TurboSync Protocol      │",
      "├─────────────────────────────────────────────┤",
      "│  libp2p · Gossipsub · Tor · Dandelion++     │",
      "├─────────────────────────────────────────────┤",
      "│     RocksDB Storage + LZ4 Compression        │",
      "└─────────────────────────────────────────────┘",
      "",
      "Not just a blockchain — a complete financial platform"
    ],
    visualCue: "Layered architecture diagram with component highlighting",
    explanation: "The full Quillon stack: Storage layer (RocksDB + LZ4), Network layer (libp2p + Tor + Dandelion++), Consensus layer (Narwhal mempool + DAG-Knight), Application layer (DEX, Banking, Bridges, Email, Smart Contracts), API layer (REST + SSE), and GUI layer (Quantum Wallet). This isn't just a blockchain — it's a complete, self-contained financial ecosystem."
  },
  {
    id: 30,
    title: "Encrypted Email System",
    duration: 45,
    content: [
      "Privacy-First Communication",
      "",
      "📧 Wallet-to-Wallet Email:",
      "   • Send encrypted messages between wallets",
      "   • No email server — messages stored on-chain",
      "   • Ed25519 authenticated (no passwords)",
      "",
      "🔐 End-to-End Encryption:",
      "   • Messages encrypted with recipient's public key",
      "   • Only recipient can decrypt with private key",
      "   • Zero knowledge of message content on-chain",
      "",
      "📎 Features:",
      "   • Rich text support",
      "   • File attachments",
      "   • Inbox, sent, drafts folders",
      "   • Reply and forward",
      "   • Thread grouping",
      "",
      "💡 Use Cases:",
      "   • Trade negotiations alongside DEX orders",
      "   • Loan communication with bank counterparties",
      "   • Private coordination between validators",
      "   • Whistleblower-safe communication"
    ],
    visualCue: "Email client screenshot with encrypted message indicators",
    explanation: "Built-in encrypted email allows wallet-to-wallet communication. Messages are encrypted with the recipient's public key and stored on-chain — no central email server that can be compromised or censored. Combined with Tor integration, this provides a complete private communication channel alongside financial transactions."
  },
  {
    id: 31,
    title: "Mainnet Launch — Live Now",
    duration: 60,
    content: [
      "Mainnet 2026.2 — Launched February 22, 2026",
      "",
      "✅ Network Status: LIVE",
      "   • 4 bootstrap nodes across 3 continents",
      "   • 27+ active miners",
      "   • 2,000,000+ blocks produced",
      "   • Zero downtime since genesis",
      "",
      "📊 Chain Parameters:",
      "   • Chain ID: 1000",
      "   • Network: mainnet2026.2",
      "   • Block time: ~1 second",
      "   • Emission: 2,625,000 QUG/year (Era 0)",
      "   • Max supply: 21,000,000 QUG",
      "",
      "🌐 Access Points:",
      "   • Wallet: https://quillon.xyz",
      "   • Code: https://code.quillon.xyz",
      "   • Technical Dive: https://technical-deepdive.quillon.xyz",
      "",
      "📥 Run Your Own Node:",
      "   wget https://quillon.xyz/downloads/q-api-server-linux-x86_64",
      "   chmod +x q-api-server-linux-x86_64",
      "   ./q-api-server-linux-x86_64 --port 8080"
    ],
    visualCue: "Live network status dashboard with real-time block counter",
    explanation: "Mainnet 2026.2 launched February 22, 2026 and is running with 4 bootstrap nodes, 27+ miners, and over 2 million blocks produced. Running your own node is as simple as downloading a single binary. The network is open, permissionless, and anyone can mine with a standard CPU."
  },
  {
    id: 32,
    title: "Development Roadmap",
    duration: 60,
    content: [
      "Milestones & Future Development:",
      "",
      "✅ Q1 2026: Mainnet Launch (COMPLETE)",
      "   • Genesis block: Feb 22, 2026",
      "   • Built-in DEX, Banking, Bridges",
      "   • Quantum Wallet GUI",
      "",
      "🔄 Q2 2026: Ecosystem Growth",
      "   • Mobile wallet (iOS + Android)",
      "   • Confidential transactions (Bulletproofs)",
      "   • Hardware wallet integration (Ledger/Trezor)",
      "   • Smart contract SDK & documentation",
      "",
      "🔮 Q4 2026: Advanced Features",
      "   • Quantum RNG integration (Phase 2)",
      "   • Layer 2 scaling (rollups)",
      "   • Cross-chain atomic swaps",
      "   • Decentralized governance (DAO)",
      "",
      "🚀 2027+: Quantum Frontier",
      "   • QKD (Quantum Key Distribution) integration",
      "   • Enterprise partnerships",
      "   • 10,000+ node scalability milestone",
      "   • Academic collaborations"
    ],
    visualCue: "Timeline roadmap with milestone markers",
    explanation: "Concrete milestones: Q1 2026 - Mainnet launched with DEX, Banking, Bridges (COMPLETE). Q2 2026 - Mobile wallets, confidential transactions, hardware wallet support. Q4 2026 - Quantum RNG integration, Layer 2 scaling, governance. 2027+ - QKD integration, enterprise adoption, 10,000+ node scalability."
  },
  {
    id: 33,
    title: "Real-World Impact & Adoption",
    duration: 60,
    content: [
      "Production Use Cases:",
      "",
      "🏦 Financial Institutions:",
      "   • High-frequency trading: need <10ms settlement",
      "   • Quillon provides 8.7ms average finality",
      "   • Post-quantum security for regulatory compliance",
      "",
      "🏛️ Government & Defense:",
      "   • Classified data with 50-year confidentiality requirement",
      "   • Harvest-now-decrypt-later threat is real",
      "   • Tor + Dandelion++ for operational security",
      "",
      "💼 Enterprise DeFi:",
      "   • Built-in DEX eliminates smart contract risk",
      "   • QUGUSD stablecoin for enterprise payments",
      "   • Cross-chain bridges for multi-chain treasury",
      "",
      "🌍 Financial Inclusion:",
      "   • Run a node on any laptop (CPU mining)",
      "   • No ASIC barrier to entry",
      "   • Free wallet with built-in banking",
      "   • Private transactions for at-risk populations"
    ],
    visualCue: "Impact map showing deployment scenarios",
    explanation: "Real-world deployment scenarios: Financial institutions need <10ms settlement (we deliver 8.7ms), governments need 50-year confidentiality (we have post-quantum crypto), enterprises need integrated DeFi (built-in DEX + banking), and underserved populations need accessible finance (CPU mining + free wallet)."
  },
  {
    id: 34,
    title: "Live Demonstration & Getting Started",
    duration: 60,
    content: [
      "Try Quillon Right Now:",
      "",
      "🚀 Quick Start — Run a Node (2 minutes):",
      "   # Download the binary",
      "   wget https://quillon.xyz/downloads/q-api-server-linux-x86_64",
      "   chmod +x q-api-server-linux-x86_64",
      "",
      "   # Start your node (auto-syncs to network)",
      "   ./q-api-server-linux-x86_64 --port 8080",
      "",
      "   # Open wallet in browser",
      "   → http://localhost:8080",
      "",
      "🌐 Use the Web Wallet:",
      "   • Visit https://quillon.xyz",
      "   • Create wallet (Ed25519 keypair generated locally)",
      "   • Start mining from the Mining tab",
      "   • Trade on the DEX, explore blocks, send email",
      "",
      "📚 Browse the Code:",
      "   • https://code.quillon.xyz (12,223 files)",
      "   • github.com/deme-plata/q-narwhalknight",
      "   • Full syntax highlighting, PDF/video viewer",
      "",
      "🛠️ Build from Source:",
      "   git clone https://code.quillon.xyz/repo.git",
      "   cargo build --release --package q-api-server"
    ],
    visualCue: "Split-screen: terminal recording + wallet dashboard",
    explanation: "Getting started is simple: download a single binary (50MB), run it, and open your browser. The node auto-syncs to the network using TurboSync. Alternatively, use the web wallet at quillon.xyz for instant access. For developers, the full source code is browseable online or buildable from source with standard Rust tooling."
  },
  {
    id: 35,
    title: "Open Source & Community",
    duration: 45,
    content: [
      "Join the Quantum Consensus Revolution!",
      "",
      "🔗 Repository Access:",
      "   • Clone: git clone https://code.quillon.xyz/repo.git",
      "   • GitHub: github.com/deme-plata/q-narwhalknight",
      "   • Browse online: https://code.quillon.xyz",
      "",
      "🌐 Ecosystem Sites:",
      "   • Wallet: https://quillon.xyz",
      "   • Technical Deep Dive: technical-deepdive.quillon.xyz",
      "   • DAG Visualization: dag.quillon.xyz",
      "",
      "🤝 Contribution Areas:",
      "   • Core protocol development (Rust)",
      "   • Post-quantum cryptography",
      "   • WASM smart contract tooling",
      "   • Bridge infrastructure",
      "   • Documentation & tutorials",
      "   • Research & academic papers",
      "",
      "💬 Community:",
      "   Discord · BitcoinTalk · GitHub Discussions",
      "   bitknight.dipper688@passmail.net"
    ],
    visualCue: "Community graphics with contribution stats",
    explanation: "Fully open source. Clone from code.quillon.xyz or GitHub. Browse all 12,223 files online. Contribution areas span core protocol (Rust), cryptography, smart contracts, bridges, docs, and research. Active community on Discord and BitcoinTalk."
  },
  {
    id: 36,
    title: "Technical Deep Dive Resources",
    duration: 45,
    content: [
      "Learn More:",
      "",
      "📄 Whitepapers:",
      "   • 'K-Parameter Emission Economics' — QUG monetary policy",
      "   • 'Apollo Sync Optimization' — TurboSync protocol design",
      "   • 'Quantum Aesthetics in Consensus Systems'",
      "   • 'Pocket Supercomputer' — Node hardware requirements",
      "",
      "🔧 Developer Guides:",
      "   • REST API reference (50+ endpoints)",
      "   • WASM smart contract SDK",
      "   • Bridge integration guide",
      "   • Mining pool protocol",
      "   • SSE real-time events reference",
      "",
      "📊 Architecture Docs:",
      "   • DAG-Knight consensus specification",
      "   • Narwhal mempool design",
      "   • Crypto-agile framework (5 phases)",
      "   • TurboSync protocol",
      "   • P2P networking & gossipsub topology"
    ],
    visualCue: "Resource grid with links and document previews",
    explanation: "Deep technical resources: multiple whitepapers covering emission economics, sync optimization, quantum aesthetics, and hardware requirements. Developer guides for the REST API (50+ endpoints), smart contract SDK, bridge integration, and mining. Architecture documentation for every major subsystem."
  },
  {
    id: 37,
    title: "Thank You!",
    duration: 10,
    content: [
      "Quillon",
      "Building the Future of Consensus",
      "",
      "⚛️  Quantum-Enhanced",
      "🚀 High-Performance (1M+ TPS, <10ms finality)",
      "🔐 Post-Quantum Secure (Dilithium5 + Kyber1024)",
      "🌐 Complete Ecosystem (DEX · Bank · Bridges · Privacy)",
      "⛏️  Fair Mining (CPU-friendly, 21M supply)",
      "",
      "Mainnet Live: https://quillon.xyz",
      "Source Code: https://code.quillon.xyz",
      "",
      "Questions?",
      "bitknight.dipper688@passmail.net",
      "",
      "⭐ Star us on GitHub!",
      "github.com/deme-plata/q-narwhalknight"
    ],
    visualCue: "Closing credits with animated quantum circuit background",
    explanation: "Final summary: Quillon is a complete blockchain ecosystem — quantum-enhanced, high-performance (1M+ TPS), post-quantum secure, with built-in DEX, banking, cross-chain bridges, privacy, and fair CPU mining. Mainnet is live at quillon.xyz. Fully open source at code.quillon.xyz.",
    centerLogo: "/logos/logo-4.png"
  }
];

export const getTotalDuration = (): number => {
  return slides.reduce((total, slide) => total + slide.duration, 0);
};
