#!/usr/bin/env node
// gen-openapi.mjs — flux-api drift-guard (A), generator half.
// Reads manifest.json (the working MCP's real endpoint surface) and emits an
// OpenAPI 3.1 document. Additive: does NOT touch src/index.ts.
//
// Usage:  node gen-openapi.mjs            # writes quillon-openapi.json next to manifest
//         node gen-openapi.mjs --print    # also prints a one-line summary
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = path.dirname(fileURLToPath(import.meta.url))
const manifest = JSON.parse(fs.readFileSync(path.join(HERE, 'manifest.json'), 'utf8'))

const okResp = { '200': { description: 'OK', content: { 'application/json': { schema: { type: 'object' } } } } }
const paths = {}
for (const ep of manifest.endpoints) {
  const method = (ep.method || 'GET').toLowerCase()
  const params = [...ep.path.matchAll(/\{([^}]+)\}/g)].map(m => ({
    name: m[1], in: 'path', required: true, schema: { type: 'string' },
  }))
  paths[ep.path] = paths[ep.path] || {}
  paths[ep.path][method] = {
    summary: `${ep.group}: ${method.toUpperCase()} ${ep.path}`,
    tags: [ep.group],
    ...(params.length ? { parameters: params } : {}),
    ...(method === 'post' ? { requestBody: { content: { 'application/json': { schema: { type: 'object' } } } } } : {}),
    responses: okResp,
  }
}

const spec = {
  openapi: '3.1.0',
  info: {
    title: manifest._meta?.title || 'Quillon Wallet API',
    version: '0.1.0',
    description: 'Generated by flux-api drift-guard from the working quillon-wallet-mcp surface. Source of truth = manifest.json. Do not hand-edit.',
  },
  servers: [{ url: manifest.base_url || 'https://quillon.xyz/api/v1' }],
  tags: [...new Set(manifest.endpoints.map(e => e.group))].map(g => ({ name: g })),
  paths,
}

const out = path.join(HERE, 'quillon-openapi.json')
fs.writeFileSync(out, JSON.stringify(spec, null, 2) + '\n')
console.log(`OpenAPI 3.1 written: ${out}  (${Object.keys(paths).length} paths, ${spec.tags.length} tags)`)
if (process.argv.includes('--print')) {
  for (const [p, ops] of Object.entries(paths)) console.log(`  ${Object.keys(ops).map(m => m.toUpperCase()).join(',').padEnd(8)} ${p}`)
}
