[package]
name = "q-wallet"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
q-types = { path = "../q-types" }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
ed25519-dalek = { workspace = true }
sha3 = { workspace = true }
rand = { workspace = true }
rand_core = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
# Using RocksDB storage instead of SQLite
q-storage = { path = "../q-storage" }
async-trait = { workspace = true }

# For mnemonic phrase generation
bip39 = "2.0"
pbkdf2 = "0.12"
hmac = "0.12"

[dev-dependencies]
proptest = { workspace = true }