#!/bin/bash
# ════════════════════════════════════════════════════════════════════════════
# Q-NarwhalKnight Testnet Staging Environment Setup
# ════════════════════════════════════════════════════════════════════════════
# This script sets up testnet.quillon.xyz for release candidate validation
# Run with: sudo ./scripts/setup-testnet.sh
# ════════════════════════════════════════════════════════════════════════════

set -e  # Exit on any error

echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║     Q-NarwhalKnight Testnet Staging Environment Setup         ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    echo "❌ Please run as root (sudo ./scripts/setup-testnet.sh)"
    exit 1
fi

# Configuration
TESTNET_DIR="/opt/orobit/testnet"
DOMAIN="testnet.quillon.xyz"
TESTNET_API_PORT=8085
TESTNET_P2P_PORT=9005
BOOTSTRAP_PEER="/ip4/185.182.185.227/tcp/9001/p2p/12D3KooWFrhdwDDTgxPX41mUyRgLcE1ozsBYArKM4DT8t4VLwuNx"

# ════════════════════════════════════════════════════════════════════════════
# STEP 1: Create Directory Structure
# ════════════════════════════════════════════════════════════════════════════
echo "📁 [1/7] Creating directory structure..."

mkdir -p "$TESTNET_DIR/q-narwhalknight"
mkdir -p "$TESTNET_DIR/frontend/dist/downloads"
mkdir -p "$TESTNET_DIR/data"
mkdir -p "$TESTNET_DIR/logs"
mkdir -p /opt/orobit/backups

echo "✅ Directories created"

# ════════════════════════════════════════════════════════════════════════════
# STEP 2: Install Dependencies
# ════════════════════════════════════════════════════════════════════════════
echo "📦 [2/7] Checking dependencies..."

# Check for nginx
if ! command -v nginx &> /dev/null; then
    echo "   Installing nginx..."
    apt-get update && apt-get install -y nginx
fi

# Check for certbot
if ! command -v certbot &> /dev/null; then
    echo "   Installing certbot..."
    apt-get update && apt-get install -y certbot python3-certbot-nginx
fi

# Check for jq
if ! command -v jq &> /dev/null; then
    echo "   Installing jq..."
    apt-get install -y jq
fi

# Check for bc
if ! command -v bc &> /dev/null; then
    echo "   Installing bc..."
    apt-get install -y bc
fi

echo "✅ Dependencies installed"

# ════════════════════════════════════════════════════════════════════════════
# STEP 3: Setup SSL Certificate
# ════════════════════════════════════════════════════════════════════════════
echo "🔐 [3/7] Setting up SSL certificate..."

# Check if certificate already exists
if [ -f "/etc/letsencrypt/live/$DOMAIN/fullchain.pem" ]; then
    echo "   Certificate already exists, skipping..."
else
    # Check if DNS is configured
    DNS_IP=$(dig +short $DOMAIN 2>/dev/null | head -1)
    CURRENT_IP=$(curl -s ifconfig.me 2>/dev/null)

    if [ "$DNS_IP" != "$CURRENT_IP" ]; then
        echo "⚠️  Warning: DNS for $DOMAIN ($DNS_IP) doesn't match server IP ($CURRENT_IP)"
        echo "   Please configure DNS before running certbot"
        echo "   Skipping SSL setup for now..."
    else
        certbot certonly --nginx -d "$DOMAIN" --non-interactive --agree-tos -m admin@quillon.xyz || {
            echo "⚠️  Certbot failed, SSL will need to be configured manually"
        }
    fi
fi

echo "✅ SSL setup complete"

# ════════════════════════════════════════════════════════════════════════════
# STEP 4: Create Nginx Configuration
# ════════════════════════════════════════════════════════════════════════════
echo "🌐 [4/7] Creating Nginx configuration..."

cat > /etc/nginx/sites-available/testnet.quillon.xyz << 'NGINX_EOF'
# ════════════════════════════════════════════════════════════════════════════
# TESTNET.QUILLON.XYZ - Staging Environment (Master Wallet Only)
# Auto-generated by setup-testnet.sh
# ════════════════════════════════════════════════════════════════════════════

# Rate limiting
limit_req_zone $binary_remote_addr zone=testnet_limit:10m rate=10r/s;

server {
    listen 80;
    server_name testnet.quillon.xyz;
    return 301 https://$server_name$request_uri;
}

server {
    listen 443 ssl http2;
    server_name testnet.quillon.xyz;

    # SSL Configuration
    ssl_certificate /etc/letsencrypt/live/testnet.quillon.xyz/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/testnet.quillon.xyz/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers off;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 1d;
    ssl_stapling on;
    ssl_stapling_verify on;

    # Security Headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header X-Environment "TESTNET-STAGING" always;
    add_header X-Robots-Tag "noindex, nofollow" always;

    # ⚠️ MASTER WALLET IP WHITELIST
    # Uncomment and configure for production use:
    # allow 192.168.1.0/24;
    # allow YOUR_MASTER_WALLET_IP;
    # deny all;

    root /opt/orobit/testnet/frontend/dist;
    index index.html;

    # API Proxy (port 8085)
    location /api/ {
        limit_req zone=testnet_limit burst=20 nodelay;
        proxy_pass http://127.0.0.1:8085/api/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }

    # SSE Streaming
    location /api/v1/sse/ {
        proxy_pass http://127.0.0.1:8085/api/v1/sse/;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Cache-Control "no-cache";
        proxy_buffering off;
        proxy_read_timeout 86400s;
        chunked_transfer_encoding off;
    }

    # WebSocket
    location /ws {
        proxy_pass http://127.0.0.1:8085/ws;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_read_timeout 86400s;
    }

    # Downloads
    location /downloads/ {
        alias /opt/orobit/testnet/frontend/dist/downloads/;
        autoindex on;
        add_header X-Release-Stage "TESTNET-CANDIDATE";
    }

    # Health check
    location /health {
        return 200 'TESTNET OK\n';
        add_header Content-Type text/plain;
    }

    # Status proxy
    location /testnet-status {
        proxy_pass http://127.0.0.1:8085/api/v1/status;
    }

    # React SPA fallback
    location / {
        try_files $uri $uri/ /index.html;
    }

    access_log /opt/orobit/testnet/logs/nginx-access.log;
    error_log /opt/orobit/testnet/logs/nginx-error.log;
}
NGINX_EOF

# Enable site
ln -sf /etc/nginx/sites-available/testnet.quillon.xyz /etc/nginx/sites-enabled/

# Test nginx config
nginx -t || {
    echo "❌ Nginx configuration test failed"
    exit 1
}

# Reload nginx
systemctl reload nginx

echo "✅ Nginx configured"

# ════════════════════════════════════════════════════════════════════════════
# STEP 5: Create Systemd Service
# ════════════════════════════════════════════════════════════════════════════
echo "⚙️  [5/7] Creating systemd service..."

cat > /etc/systemd/system/q-testnet-server.service << SERVICE_EOF
[Unit]
Description=Q-NarwhalKnight Testnet API Server (Staging)
After=network.target
Wants=network-online.target

[Service]
Type=simple
User=root
WorkingDirectory=/opt/orobit/testnet/q-narwhalknight
Environment=RUST_LOG=info
Environment=Q_NETWORK_ID=testnet-staging
Environment=Q_DATA_DIR=/opt/orobit/testnet/data
Environment=Q_IS_STAGING=true
Environment=Q_PREFLIGHT_CHECK=1

ExecStart=/opt/orobit/testnet/q-narwhalknight/q-api-server-candidate \\
    --port $TESTNET_API_PORT \\
    --p2p-port $TESTNET_P2P_PORT \\
    --bootstrap-peer $BOOTSTRAP_PEER \\
    --data-dir /opt/orobit/testnet/data \\
    --network testnet-staging

Restart=always
RestartSec=10
StandardOutput=journal
StandardError=journal
SyslogIdentifier=q-testnet

[Install]
WantedBy=multi-user.target
SERVICE_EOF

systemctl daemon-reload
echo "✅ Systemd service created"

# ════════════════════════════════════════════════════════════════════════════
# STEP 6: Create Validation Scripts
# ════════════════════════════════════════════════════════════════════════════
echo "📜 [6/7] Creating validation scripts..."

# Sync validation cron script
cat > /opt/orobit/testnet/validate-sync.sh << 'VALIDATE_EOF'
#!/bin/bash
# Testnet Sync Validation - Run hourly via cron
# Add to crontab: 0 * * * * /opt/orobit/testnet/validate-sync.sh

LOG_DIR="/opt/orobit/testnet/logs"
TIMESTAMP=$(date +%Y-%m-%d_%H:%M:%S)
LOG_FILE="$LOG_DIR/sync-validation.log"

# Get heights
TESTNET_HEIGHT=$(curl -s http://127.0.0.1:8085/api/v1/status 2>/dev/null | jq -r '.height // 0')
PROD_HEIGHT=$(curl -s http://127.0.0.1:8080/api/v1/status 2>/dev/null | jq -r '.height // 0')

# Check for sync-down
PREV_HEIGHT_FILE="$LOG_DIR/last-height.txt"
if [ -f "$PREV_HEIGHT_FILE" ]; then
    PREV_HEIGHT=$(cat "$PREV_HEIGHT_FILE")
    if [ "$TESTNET_HEIGHT" -lt "$PREV_HEIGHT" ] && [ "$PREV_HEIGHT" -gt 100 ]; then
        echo "[$TIMESTAMP] ❌ CRITICAL: SYNC-DOWN from $PREV_HEIGHT to $TESTNET_HEIGHT" >> "$LOG_FILE"
        # Could add alerting here (email, Slack, etc.)
        exit 1
    fi
fi
echo "$TESTNET_HEIGHT" > "$PREV_HEIGHT_FILE"

# Calculate sync percentage
if [ "$PROD_HEIGHT" -gt 0 ]; then
    SYNC_PCT=$(echo "scale=2; ($TESTNET_HEIGHT / $PROD_HEIGHT) * 100" | bc)
else
    SYNC_PCT="0"
fi

# Get peer count
PEERS=$(curl -s http://127.0.0.1:8085/api/v1/peers 2>/dev/null | jq -r '.connected_peers // 0')

# Memory usage
RSS_KB=$(ps aux | grep q-api-server-candidate | grep -v grep | awk '{print $6}' | head -1)
RSS_MB=$(echo "scale=0; ${RSS_KB:-0} / 1024" | bc)

# Log status
echo "[$TIMESTAMP] Testnet: $TESTNET_HEIGHT | Prod: $PROD_HEIGHT | Sync: ${SYNC_PCT}% | Peers: $PEERS | Mem: ${RSS_MB}MB" >> "$LOG_FILE"

# Trim log file to last 1000 lines
tail -1000 "$LOG_FILE" > "$LOG_FILE.tmp" && mv "$LOG_FILE.tmp" "$LOG_FILE"
VALIDATE_EOF

chmod +x /opt/orobit/testnet/validate-sync.sh

# Create testnet frontend placeholder
cat > "$TESTNET_DIR/frontend/dist/index.html" << 'HTML_EOF'
<!DOCTYPE html>
<html>
<head>
    <title>Q-NarwhalKnight Testnet</title>
    <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%);
            color: white;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            min-height: 100vh;
            margin: 0;
        }
        .banner {
            background: linear-gradient(90deg, #ff6b00, #ff0000);
            color: white;
            padding: 10px 20px;
            text-align: center;
            font-weight: bold;
            position: fixed;
            top: 0;
            left: 0;
            right: 0;
            z-index: 1000;
        }
        .container {
            text-align: center;
            padding: 40px;
            background: rgba(255,255,255,0.1);
            border-radius: 20px;
            margin-top: 60px;
        }
        h1 { color: #00d4ff; }
        .status { margin: 20px 0; font-size: 18px; }
        .success { color: #00ff88; }
        .warning { color: #ffaa00; }
        code {
            background: rgba(0,0,0,0.3);
            padding: 2px 8px;
            border-radius: 4px;
        }
    </style>
</head>
<body>
    <div class="banner">
        ⚠️ TESTNET STAGING ENVIRONMENT - Release Candidate Testing Only ⚠️
    </div>
    <div class="container">
        <h1>🧪 Q-NarwhalKnight Testnet</h1>
        <div class="status">
            <p>This is the staging environment for release validation.</p>
            <p class="warning">Master Wallet Access Only</p>
        </div>
        <div id="status-info">
            <p>Loading status...</p>
        </div>
    </div>
    <script>
        async function updateStatus() {
            try {
                const res = await fetch('/api/v1/status');
                const data = await res.json();
                document.getElementById('status-info').innerHTML = `
                    <p class="success">✅ API Online</p>
                    <p>Height: <code>${data.height || 'N/A'}</code></p>
                    <p>Version: <code>${data.version || 'N/A'}</code></p>
                `;
            } catch (e) {
                document.getElementById('status-info').innerHTML =
                    '<p class="warning">⚠️ API Offline or starting...</p>';
            }
        }
        updateStatus();
        setInterval(updateStatus, 10000);
    </script>
</body>
</html>
HTML_EOF

echo "✅ Validation scripts created"

# ════════════════════════════════════════════════════════════════════════════
# STEP 7: Setup Cron for Hourly Validation
# ════════════════════════════════════════════════════════════════════════════
echo "⏰ [7/7] Setting up cron job..."

# Add cron job for hourly sync validation
CRON_LINE="0 * * * * /opt/orobit/testnet/validate-sync.sh"
(crontab -l 2>/dev/null | grep -v "validate-sync.sh"; echo "$CRON_LINE") | crontab -

echo "✅ Cron job configured"

# ════════════════════════════════════════════════════════════════════════════
# SETUP COMPLETE
# ════════════════════════════════════════════════════════════════════════════
echo ""
echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║         ✅ TESTNET SETUP COMPLETE                             ║"
echo "╠═══════════════════════════════════════════════════════════════╣"
echo "║                                                               ║"
echo "║  Directory: /opt/orobit/testnet/                              ║"
echo "║  Domain: https://testnet.quillon.xyz                          ║"
echo "║  API Port: 8085                                               ║"
echo "║  P2P Port: 9005                                               ║"
echo "║                                                               ║"
echo "║  Next Steps:                                                  ║"
echo "║  1. Build release candidate binary                            ║"
echo "║  2. Copy to /opt/orobit/testnet/q-narwhalknight/              ║"
echo "║     as q-api-server-candidate                                 ║"
echo "║  3. Start service: systemctl start q-testnet-server           ║"
echo "║  4. Monitor: journalctl -u q-testnet-server -f                ║"
echo "║                                                               ║"
echo "║  Validation Log: /opt/orobit/testnet/logs/sync-validation.log ║"
echo "║                                                               ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
