[package]
name = "q-network"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
q-types = { path = "../q-types" }
q-narwhal-core = { path = "../q-narwhal-core" }
q-dag-knight = { path = "../q-dag-knight" }

# Networking
libp2p = { workspace = true }
libp2p-quic = { workspace = true }

# Async runtime
tokio = { workspace = true }
futures = { workspace = true }

# Serialization
serde = { workspace = true }
serde_json = { workspace = true }
postcard = { workspace = true }
uuid = { workspace = true }

# Cryptography - Phase 0 (Classical)
ed25519-dalek = { workspace = true }
sha3 = { workspace = true }

# Cryptography - Phase 1 (Post-Quantum)
pqcrypto-dilithium = { workspace = true }
pqcrypto-kyber = { workspace = true }

# Error handling
anyhow = { workspace = true }
thiserror = { workspace = true }

# Logging
tracing = { workspace = true }

# Async utilities
async-trait = { workspace = true }

# Time and utilities
chrono = { workspace = true }
rand = { workspace = true }

[dev-dependencies]
tokio-test = "0.4"
proptest = { workspace = true }